import { FileIcons } from '../models/index';

/**
 * Defines file icons
 */
export const fileIcons: FileIcons = {
  defaultIcon: { name: 'file' },
  icons: [
    // region [Custom]
    {
      name: 'githubActions',
      fileNames: [
        '.github/build.yaml',
        '.github/build.yml',
        '.github/ci.yaml',
        '.github/ci.yml',
        '.github/config.yaml',
        '.github/config.yml',
        '.github/main.yaml',
        '.github/main.yml',
        '.github/release.yaml',
        '.github/release.yml',
        '.github/workflow.yaml',
        '.github/workflow.yml',
      ],
    },
    {
      name: 'githubCode',
      fileNames: ['CODE_OF_CONDUCT.md', 'CODE_OF_CONDUCT.txt'],
    },
    {
      name: 'githubContributing',
      fileNames: ['CONTRIBUTING.md', 'CONTRIBUTING.txt'],
    },
    {
      name: 'github',
      fileNames: [
        'COMMIT_MESSAGE_TEMPLATE.md',
        'COMMIT_MESSAGE_TEMPLATE.txt',
        'PULL_REQUEST_TEMPLATE.md',
        'PULL_REQUEST_TEMPLATE.txt',
        'TEMPLATE.md',
        'TEMPLATE.txt',
      ],
      light: true,
    },
    {
      name: 'readme',
      fileNames: [
        'README',
        'README.md',
        'README.txt',
        'readme',
        'readme.md',
        'readme.txt',
      ],
      light: true,
    },
    {
      name: 'gitcommit',
      fileNames: ['COMMIT_EDITMSG', 'ATOM_COMMIT_EDITMSG'],
    },
    {
      name: 'githubCommit',
      fileNames: [
        'COMMIT_MESSAGE_CONVENTION.md',
        'COMMIT_MESSAGE_CONVENTION.txt',
      ],
    },
    {
      name: 'gitmerge',
      fileNames: ['MERGE_HEAD', 'MERGE_MODE', 'MERGE_MSG'],
    },
    {
      name: 'install',
      fileNames: [
        'INSTALL',
        'INSTALL.md',
        'INSTALL.sh',
        'INSTALL.txt',
        'INSTALL.yaml',
        'INSTALL.yml',
        'install',
        'install.md',
        'install.sh',
        'install.txt',
        'install.yaml',
        'install.yml',
      ],
    },
    {
      name: 'funding',
      fileNames: [
        'FUNDING',
        'FUNDING.md',
        'FUNDING.sh',
        'FUNDING.txt',
        'FUNDING.yaml',
        'FUNDING.yml',
        'funding',
        'funding.md',
        'funding.sh',
        'funding.txt',
        'funding.yaml',
        'funding.yml',
      ],
    },
    {
      name: 'stalebot',
      fileNames: ['stale.yml', 'stale.yaml'],
    },
    {
      name: 'plugin',
      fileNames: ['META-INF/plugin.xml'],
    },
    {
      name: 'i18nProperties',
      fileExtensions: ['bundle.properties', 'messages/properties'],
    },
    {
      name: 'i18nJava',
      fileExtensions: ['bundle.java', 'messages/java'],
    },
    {
      name: 'i18nKotlin',
      fileExtensions: ['bundle.kt', 'messages/kt'],
    },
    // endregion [Custom]

    // region [0-9]
    {
      name: '11ty',
      fileNames: [
        '.11ty.cjs',
        '.11ty.js',
        '.11ty.mjs',
        '.11ty.ts',
        '.11tyignore',
        '.eleventy.cjs',
        '.eleventy.js',
        '.eleventy.mjs',
        '.eleventy.ts',
        '.eleventyignore',
      ],
      light: true,
    },
    {
      name: '1c',
      fileExtensions: ['bsl', 'mdo', 'sdbl', 'os'],
    },
    {
      name: '3d',
      fileExtensions: [
        'ac',
        'c4d',
        'cginc',
        'dxf',
        'geo',
        'obj',
        'shader',
        'stl',
        'tesc',
        'tese',
        'x',
      ],
    },
    {
      name: '3dsmax',
      fileExtensions: ['osl', 'dwg', '3ds'],
    },
    {
      name: '4d',
      fileExtensions: ['4dm', '4db'],
    },

    // endregion [0-9]

    // region [A]
    {
      name: 'aplus',
      fileExtensions: [
        'a+',
        'a',
      ],
    },
    {
      name: 'access',
      fileExtensions: [
        'accda',
        'accdb',
        'accde',
        'accdr',
        'accdt',
        'adn',
        'laccdb',
        'maf',
        'mam',
        'maq',
        'mar',
        'mdw',
      ],
    },
    {
      name: 'abap',
      fileExtensions: [
        'abap',
        'abp',
      ],
    },
    {
      name: 'abc',
      fileExtensions: [
        'abc',
      ],
    },
    {
      name: 'abif',
      fileExtensions: [
        'ab1',
        'abif',
        'fsa',
      ],
    },
    {
      name: 'acre',
      fileNames: [
        'acre.config',
      ],
    },
    {
      name: 'actionscript',
      fileExtensions: [
        'as',
        'as3',
        'jsfl',
      ],
    },
    {
      name: 'ada',
      fileExtensions: [
        'ada',
        'adb',
        'ads',
      ],
    },
    {
      name: 'animate',
      fileExtensions: [
        'fla',
        'xfl',
      ],
    },
    {
      name: 'ae',
      fileExtensions: [
        'aep',
        'aet',
      ],
    },
    {
      name: 'ai',
      fileExtensions: [
        'ai',
        'aia',
        'ait',
      ],
    },
    {
      name: 'indesign',
      fileExtensions: [
        'id',
        'idml',
        'indb',
        'indd',
        'indl',
        'indt',
      ],
    },
    {
      name: 'psd',
      fileExtensions: [
        'atn',
        'psb',
        'psd',
      ],
    },
    {
      name: 'premiere',
      fileExtensions: [
        'prel',
        'prproj',
        'psq',
      ],
    },
    {
      name: 'advpl',
      fileExtensions: [
        'ahu',
        'aph',
        'prw',
        'tlpp',
      ],
    },
    {
      name: 'affectscript',
      fileExtensions: [
        'affect',
      ],
    },
    {
      name: 'affinity',
      fileExtensions: [
        'afdesign',
        'afphoto',
        'afpub',
      ],
    },
    {
      name: 'agda',
      fileExtensions: [
        'agda',
        'lagda',
      ],
    },
    {
      name: 'akka',
      fileExtensions: [
        'akka',
      ],
    },
    {
      name: 'al',
      fileExtensions: [
        'al',
      ],
    },

    // endregion

    //
    // {
    //   fileExtensions: [
    //     'ac',
    //     'blend',
    //     'fbx',
    //     'mesh',
    //     'mqo',
    //     'obj',
    //     'pmd',
    //     'pmx',
    //     'skp',
    //     'stl',
    //     'stp',
    //     'vac',
    //     'vdp',
    //     'vox',
    //   ],
    //   name: '3d',
    // },
    // {
    //   fileExtensions: ['apk', 'smali', 'dex'],
    //   fileNames: ['androidmanifest.xml'],
    //   name: 'android',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['module.ts', 'module.js', 'ng-template'],
    //   fileNames: ['angular-cli.json', '.angular-cli.json', 'angular.json'],
    //   name: 'angular',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['component.ts', 'component.js'],
    //   name: 'angular-component',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['directive.ts', 'directive.js'],
    //   name: 'angular-directive',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['guard.ts', 'guard.js'],
    //   name: 'angular-guard',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['pipe.ts', 'pipe.js', 'filter.js'],
    //   name: 'angular-pipe',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['resolver.ts', 'resolver.js'],
    //   name: 'angular-resolver',
    // },
    // {
    //   enabledFor: [IconPack.Angular, IconPack.Ngrx],
    //   fileExtensions: ['service.ts', 'service.js'],
    //   name: 'angular-service',
    // },
    // {
    //   fileNames: [
    //     'architecture',
    //     'architecture.md',
    //     'architecture.rst',
    //     'architecture.txt',
    //   ],
    //   name: 'architecture',
    // },
    // {
    //   fileExtensions: [
    //     'a51',
    //     'aea',
    //     'agc',
    //     'ags',
    //     'argus',
    //     'asm',
    //     'binsource',
    //     'inc',
    //     'mitigus',
    //     'ms',
    //     'nasm',
    //     's',
    //   ],
    //   name: 'assembly',
    // },
    // {
    //   fileExtensions: ['astro'],
    //   fileNames: [
    //     'astro.config.cjs',
    //     'astro.config.cts',
    //     'astro.config.js',
    //     'astro.config.mjs',
    //     'astro.config.mts',
    //     'astro.config.ts',
    //   ],
    //   name: 'astro',
    // },
    // {
    //   fileExtensions: ['mp3', 'flac', 'm4a', 'wma', 'aiff', 'wav'],
    //   name: 'audio',
    // },
    // {
    //   fileNames: [
    //     'authors',
    //     'authors.md',
    //     'authors.rst',
    //     'authors.txt',
    //     'contributors',
    //     'contributors.md',
    //     'contributors.rst',
    //     'contributors.txt',
    //   ],
    //   name: 'authors',
    // },
    // {
    //   fileNames: [
    //     '.autorc',
    //     'auto-config.js',
    //     'auto-config.json',
    //     'auto-config.ts',
    //     'auto-config.yaml',
    //     'auto-config.yml',
    //     'auto.config.js',
    //     'auto.config.ts',
    //   ],
    //   light: true,
    //   name: 'auto',
    // },
    // {
    //   fileExtensions: ['azure-pipelines.yml', 'azure-pipelines.yaml'],
    //   fileNames: ['azure-pipelines.yml', 'azure-pipelines.yaml'],
    //   name: 'azure-pipelines',
    // },
    // {
    //   fileNames: [
    //     '.babel-plugin-macrosrc',
    //     '.babel-plugin-macrosrc.js',
    //     '.babel-plugin-macrosrc.json',
    //     '.babel-plugin-macrosrc.yaml',
    //     '.babel-plugin-macrosrc.yml',
    //     '.babelrc',
    //     '.babelrc.cjs',
    //     '.babelrc.js',
    //     '.babelrc.json',
    //     '.babelrc.mjs',
    //     'babel-plugin-macros.config.js',
    //     'babel-transform.js',
    //     'babel.config.cjs',
    //     'babel.config.js',
    //     'babel.config.json',
    //     'babel.config.mjs',
    //   ],
    //   name: 'babel',
    // },
    // {
    //   fileExtensions: ['bzl', 'bazel'],
    //   fileNames: ['.bazelignore', '.bazelrc', '.bazelversion'],
    //   name: 'bazel',
    // },
    // {
    //   fileNames: ['bitbucket-pipelines.yaml', 'bitbucket-pipelines.yml'],
    //   name: 'bitbucket',
    // },
    // {
    //   fileNames: [
    //     '.blitz.config.compiled.js',
    //     'blitz.config.js',
    //     'blitz.config.ts',
    //   ],
    //   name: 'blitz',
    // },
    // {
    //   fileNames: ['browserslist', '.browserslistrc'],
    //   light: true,
    //   name: 'browserlist',
    // },
    // {
    //   fileExtensions: ['cabal'],
    //   fileNames: [
    //     'cabal.project',
    //     'cabal.project.freeze',
    //     'cabal.project.local',
    //   ],
    //   name: 'cabal',
    // },
    // {
    //   fileNames: ['capacitor.config.json', 'capacitor.config.ts'],
    //   name: 'capacitor',
    // },
    // {
    //   fileExtensions: ['cer', 'cert', 'crt'],
    //   fileNames: [
    //     'copying',
    //     'copying.md',
    //     'copying.rst',
    //     'copying.txt',
    //     'copyright',
    //     'copyright.md',
    //     'copyright.rst',
    //     'copyright.txt',
    //     'licence',
    //     'licence-agpl',
    //     'licence-apache',
    //     'licence-bsd',
    //     'licence-gpl',
    //     'licence-lgpl',
    //     'licence-mit',
    //     'licence.md',
    //     'licence.rst',
    //     'licence.txt',
    //     'license',
    //     'license-agpl',
    //     'license-apache',
    //     'license-bsd',
    //     'license-gpl',
    //     'license-lgpl',
    //     'license-mit',
    //     'license.md',
    //     'license.rst',
    //     'license.txt',
    //   ],
    //   name: 'certificate',
    // },
    // {
    //   fileNames: [
    //     'changelog',
    //     'changelog.md',
    //     'changelog.rst',
    //     'changelog.txt',
    //     'changes',
    //     'changes.md',
    //     'changes.rst',
    //     'changes.txt',
    //   ],
    //   name: 'changelog',
    // },
    // {
    //   fileExtensions: ['cmake'],
    //   fileNames: ['cmakelists.txt', 'cmakecache.txt'],
    //   name: 'cmake',
    // },
    // {
    //   fileNames: [
    //     '.commitlint.yaml',
    //     '.commitlint.yml',
    //     '.commitlintrc',
    //     '.commitlintrc.cjs',
    //     '.commitlintrc.cts',
    //     '.commitlintrc.js',
    //     '.commitlintrc.json',
    //     '.commitlintrc.ts',
    //     '.commitlintrc.yaml',
    //     '.commitlintrc.yml',
    //     'commitlint.config.cjs',
    //     'commitlint.config.cts',
    //     'commitlint.config.js',
    //     'commitlint.config.ts',
    //   ],
    //   name: 'commitlint',
    // },
    // {
    //   fileNames: ['code_of_conduct.md', 'code_of_conduct.txt'],
    //   name: 'conduct',
    // },
    // {
    //   fileExtensions: [
    //     'awk',
    //     'bash',
    //     'bat',
    //     'cmd',
    //     'csh',
    //     'exp',
    //     'fish',
    //     'ksh',
    //     'sh',
    //     'tcsh',
    //     'zsh',
    //   ],
    //   fileNames: ['commit-msg', 'pre-commit', 'pre-push', 'post-merge'],
    //   name: 'console',
    // },
    // {
    //   fileNames: [
    //     'contributing',
    //     'contributing.md',
    //     'contributing.rst',
    //     'contributing.txt',
    //   ],
    //   name: 'contributing',
    // },
    // {
    //   fileExtensions: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
    //   name: 'cpp',
    // },
    // {
    //   fileNames: ['credits.md', 'credits.rst', 'credits.txt', 'credits'],
    //   name: 'credits',
    // },
    // {
    //   fileNames: [
    //     'cypress.config.cjs',
    //     'cypress.config.js',
    //     'cypress.config.mjs',
    //     'cypress.config.ts',
    //     'cypress.env.json',
    //     'cypress.json',
    //   ],
    //   name: 'cypress',
    // },
    // {
    //   fileExtensions: [
    //     'accdb',
    //     'db',
    //     'db3',
    //     'mdb',
    //     'pdb',
    //     'pgsql',
    //     'pkb',
    //     'pks',
    //     'postgres',
    //     'psql',
    //     'sql',
    //     'sqlite',
    //     'sqlite3',
    //   ],
    //   name: 'database',
    // },
    // {
    //   fileExtensions: ['bubble', 'html.bubble', 'php.bubble'],
    //   name: 'dinophp',
    // },
    // {
    //   fileExtensions: ['dockerignore', 'dockerfile'],
    //   fileNames: [
    //     'compose.yaml',
    //     'compose.yml',
    //     'docker-compose.alpha.yaml',
    //     'docker-compose.alpha.yml',
    //     'docker-compose.beta.yaml',
    //     'docker-compose.beta.yml',
    //     'docker-compose.ci.yaml',
    //     'docker-compose.ci.yml',
    //     'docker-compose.dev.yaml',
    //     'docker-compose.dev.yml',
    //     'docker-compose.development.yaml',
    //     'docker-compose.development.yml',
    //     'docker-compose.local.yaml',
    //     'docker-compose.local.yml',
    //     'docker-compose.override.yaml',
    //
    //     'docker-compose.override.yml',
    //     'docker-compose.prod.yaml',
    //     'docker-compose.prod.yml',
    //     'docker-compose.production.yaml',
    //     'docker-compose.production.yml',
    //     'docker-compose.stage.yaml',
    //     'docker-compose.stage.yml',
    //     'docker-compose.staging.yaml',
    //     'docker-compose.staging.yml',
    //     'docker-compose.test.yaml',
    //     'docker-compose.test.yml',
    //     'docker-compose.testing.yaml',
    //     'docker-compose.testing.yml',
    //     'docker-compose.web.yaml',
    //     'docker-compose.web.yml',
    //     'docker-compose.worker.yaml',
    //
    //     'docker-compose.worker.yml',
    //     'docker-compose.yaml',
    //     'docker-compose.yml',
    //     'dockerfile',
    //     'dockerfile.alpha',
    //     'dockerfile.beta',
    //     'dockerfile.ci',
    //     'dockerfile.dev',
    //     'dockerfile.development',
    //     'dockerfile.local',
    //     'dockerfile.prod',
    //     'dockerfile.production',
    //     'dockerfile.stage',
    //     'dockerfile.staging',
    //     'dockerfile.test',
    //     'dockerfile.testing',
    //
    //     'dockerfile.web',
    //     'dockerfile.worker',
    //   ],
    //   name: 'docker',
    // },
    // {
    //   fileExtensions: ['drone.yml'],
    //   fileNames: ['.drone.yml'],
    //   light: true,
    //   name: 'drone',
    // },
    // {
    //   fileNames: [
    //     'dune',
    //     'dune-project',
    //     'dune-workspace',
    //     'dune-workspace.dev',
    //   ],
    //   name: 'dune',
    // },
    // {
    //   fileNames: ['.ember-cli', '.ember-cli.js', 'ember-cli-builds.js'],
    //   name: 'ember',
    // },
    // {
    //   fileNames: [
    //     '.eslintcache',
    //     '.eslintignore',
    //     '.eslintrc',
    //     '.eslintrc-jsdoc.js',
    //     '.eslintrc-md.js',
    //     '.eslintrc.cjs',
    //     '.eslintrc.js',
    //     '.eslintrc.json',
    //     '.eslintrc.yaml',
    //     '.eslintrc.yml',
    //     'eslint.config.js',
    //   ],
    //   name: 'eslint',
    // },
    // {
    //   fileExtensions: ['fig'],
    //   name: 'figma',
    // },
    // {
    //   fileNames: [
    //     '.firebaserc',
    //     'firebase.json',
    //     'firestore.indexes.json',
    //     'firestore.rules',
    //   ],
    //   name: 'firebase',
    // },
    // {
    //   fileExtensions: [
    //     'bmap',
    //     'eot',
    //     'fnt',
    //     'font',
    //     'fonts',
    //     'mrf',
    //     'ntf',
    //     'odttf',
    //     'otf',
    //     'sui',
    //     'suit',
    //     'ttc',
    //     'ttf',
    //     'woff',
    //     'woff2',
    //   ],
    //   name: 'font',
    // },
    // {
    //   fileExtensions: ['f', 'f77', 'f90', 'f95', 'f03', 'f08'],
    //   name: 'fortran',
    // },
    // {
    //   fileNames: [
    //     'gatsby-browser.js',
    //     'gatsby-config.js',
    //     'gatsby-config.ts',
    //     'gatsby-node.js',
    //     'gatsby-ssr.js',
    //   ],
    //   name: 'gatsby',
    // },
    // {
    //   fileExtensions: ['patch'],
    //   fileNames: [
    //     '.gitattributes',
    //     '.gitconfig',
    //     '.gitignore',
    //     '.gitignore-global',
    //     '.gitignore_global',
    //     '.gitinclude',
    //     '.gitkeep',
    //     '.gitmodules',
    //     'git-history',
    //   ],
    //   name: 'git',
    // },
    // {
    //   fileNames: ['go.mod', 'go.sum', 'go.work', 'go.work.sum'],
    //   name: 'go-mod',
    // },
    // {
    //   fileExtensions: ['gradle'],
    //   fileNames: ['gradle.properties', 'gradlew', 'gradle-wrapper.properties'],
    //   name: 'gradle',
    // },
    // {
    //   fileExtensions: ['graphcool'],
    //   fileNames: ['project.graphcool'],
    //   name: 'graphcool',
    // },
    // {
    //   fileExtensions: ['graphql', 'gql'],
    //   fileNames: [
    //     '.graphqlconfig',
    //     '.graphqlrc',
    //     '.graphqlrc.cjs',
    //     '.graphqlrc.js',
    //     '.graphqlrc.json',
    //     '.graphqlrc.toml',
    //     '.graphqlrc.ts',
    //     '.graphqlrc.yaml',
    //     '.graphqlrc.yml',
    //     'graphql.config.js',
    //     'graphql.config.json',
    //     'graphql.config.toml',
    //     'graphql.config.ts',
    //     'graphql.config.yaml',
    //     'graphql.config.yml',
    //   ],
    //   name: 'graphql',
    // },
    // {
    //   fileNames: ['gridsome.config.js', 'gridsome.server.js'],
    //   name: 'gridsome',
    // },
    // {
    //   fileNames: [
    //     'gruntfile.babel.coffee',
    //     'gruntfile.babel.js',
    //     'gruntfile.babel.ts',
    //     'gruntfile.coffee',
    //     'gruntfile.js',
    //     'gruntfile.ts',
    //   ],
    //   name: 'grunt',
    // },
    // {
    //   fileNames: [
    //     'gulpfile.babel.js',
    //     'gulpfile.cts',
    //     'gulpfile.js',
    //     'gulpfile.mjs',
    //     'gulpfile.mts',
    //     'gulpfile.ts',
    //   ],
    //   name: 'gulp',
    // },
    // {
    //   fileExtensions: ['horusec-config.json'],
    //   fileNames: ['horusec-config.json'],
    //   name: 'horusec',
    // },
    // {
    //   fileExtensions: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
    //   name: 'hpp',
    // },
    // {
    //   fileNames: [
    //     '.huskyrc',
    //     '.huskyrc.js',
    //     '.huskyrc.json',
    //     '.huskyrc.yaml',
    //     '.huskyrc.yml',
    //     'husky.config.js',
    //   ],
    //   name: 'husky',
    // },
    // {
    //   fileExtensions: [
    //     'afphoto',
    //     'ami',
    //     'apx',
    //     'ase',
    //     'aseprite',
    //     'avif',
    //     'bmp',
    //     'bpg',
    //     'brk',
    //     'clip',
    //     'cpt',
    //     'cur',
    //     'dds',
    //     'dng',
    //     'eps',
    //     'exr',
    //     'fpx',
    //     'gbr',
    //     'gif',
    //     'heic',
    //     'heif',
    //     'ico',
    //     'img',
    //     'jb2',
    //     'jbig2',
    //     'jfif',
    //     'jng',
    //     'jpeg',
    //     'jpg',
    //     'jxr',
    //     'kra',
    //     'mdp',
    //     'ora',
    //     'pbm',
    //     'pdn',
    //     'pgf',
    //     'pgm',
    //     'pic',
    //     'png',
    //     'pnm',
    //     'ppm',
    //     'psb',
    //     'psd',
    //     'raw',
    //     'reb',
    //     'sai',
    //     'tga',
    //     'tif',
    //     'tiff',
    //     'webp',
    //     'xcf',
    //   ],
    //   name: 'image',
    // },
    // {
    //   fileExtensions: ['js.map', 'mjs.map', 'cjs.map'],
    //   name: 'javascript-map',
    // },
    // {
    //   fileExtensions: ['jenkinsfile', 'jenkins'],
    //   fileNames: ['jenkinsfile'],
    //   name: 'jenkins',
    // },
    // {
    //   fileNames: [
    //     '.jestrc',
    //     '.jestrc.js',
    //     '.jestrc.json',
    //     'jest-e2e.config.cjs',
    //     'jest-e2e.config.cts',
    //     'jest-e2e.config.js',
    //     'jest-e2e.config.json',
    //     'jest-e2e.config.mjs',
    //     'jest-e2e.config.mts',
    //     'jest-e2e.config.ts',
    //     'jest-e2e.json',
    //     'jest-github-actions-reporter.js',
    //     'jest-unit.config.js',
    //     'jest.config.cjs',
    //     'jest.config.cts',
    //     'jest.config.js',
    //     'jest.config.json',
    //     'jest.config.mjs',
    //     'jest.config.mts',
    //     'jest.config.ts',
    //     'jest.e2e.config.cjs',
    //     'jest.e2e.config.cts',
    //     'jest.e2e.config.js',
    //     'jest.e2e.config.json',
    //     'jest.e2e.config.mjs',
    //     'jest.e2e.config.mts',
    //     'jest.e2e.config.ts',
    //     'jest.e2e.json',
    //     'jest.json',
    //     'jest.setup.js',
    //     'jest.setup.ts',
    //     'jest.teardown.js',
    //   ],
    //   name: 'jest',
    // },
    // {
    //   fileExtensions: ['jinja', 'jinja2', 'j2', 'jinja-html'],
    //   light: true,
    //   name: 'jinja',
    // },
    // {
    //   fileExtensions: ['jsconfig.json'],
    //   fileNames: ['jsconfig.json'],
    //   name: 'jsconfig',
    // },
    // {
    //   fileExtensions: [
    //     'json',
    //     'json5',
    //     'jsonc',
    //     'jsonl',
    //     'ndjson',
    //     'tsbuildinfo',
    //   ],
    //   fileNames: [
    //     '.esformatter',
    //     '.jsbeautifyrc',
    //     '.jscsrc',
    //     '.jshintrc',
    //     '.lintstagedrc',
    //     'cdp.pid',
    //     'composer.lock',
    //   ],
    //   name: 'json',
    // },
    // {
    //   fileNames: [
    //     'karma-main.js',
    //     'karma-main.ts',
    //     'karma.conf.coffee',
    //     'karma.conf.js',
    //     'karma.conf.ts',
    //     'karma.config.js',
    //     'karma.config.ts',
    //   ],
    //   name: 'karma',
    // },
    // {
    //   fileExtensions: ['pub', 'key', 'pem', 'asc', 'gpg', 'passwd'],
    //   fileNames: ['.htpasswd'],
    //   name: 'key',
    // },
    // {
    //   fileExtensions: ['blade.php', 'inky.php'],
    //   fileNames: ['artisan'],
    //   name: 'laravel',
    // },
    // {
    //   fileNames: [
    //     '.lighthouserc.js',
    //     '.lighthouserc.json',
    //     '.lighthouserc.yaml',
    //     '.lighthouserc.yml',
    //     'lighthouserc.js',
    //     'lighthouserc.json',
    //     'lighthouserc.yaml',
    //     'lighthouserc.yml',
    //   ],
    //   name: 'lighthouse',
    // },
    // {
    //   fileExtensions: ['lock'],
    //   fileNames: ['security.md', 'security.txt', 'security'],
    //   name: 'lock',
    // },
    // {
    //   fileExtensions: ['mk'],
    //   fileNames: ['makefile', 'gnumakefile', 'kbuild'],
    //   name: 'makefile',
    // },
    // {
    //   fileExtensions: ['md', 'markdown', 'rst'],
    //   name: 'markdown',
    // },
    // {
    //   fileNames: ['maven.config', 'jvm.config', 'pom.xml'],
    //   name: 'maven',
    // },
    // {
    //   fileExtensions: ['wrap'],
    //   fileNames: ['meson.build', 'meson_options.txt'],
    //   name: 'meson',
    // },
    // {
    //   fileExtensions: [
    //     'mca',
    //     'mcfunction',
    //     'mcgame',
    //     'mclevel',
    //     'mcmeta',
    //     'mcr',
    //     'mcstructure',
    //     'mcworld',
    //     'mine',
    //     'mus',
    //   ],
    //   fileNames: ['.mcattributes', '.mcdefinitions', '.mcignore'],
    //   name: 'minecraft',
    // },
    // {
    //   fileExtensions: ['mjml'],
    //   fileNames: ['.mjmlconfig'],
    //   name: 'mjml',
    // },
    // {
    //   fileNames: [
    //     '.mocharc.js',
    //     '.mocharc.json',
    //     '.mocharc.jsonc',
    //     '.mocharc.yaml',
    //     '.mocharc.yml',
    //     'mocha.opts',
    //   ],
    //   name: 'mocha',
    // },
    // {
    //   fileNames: ['.modernizrrc', '.modernizrrc.js', '.modernizrrc.json'],
    //   name: 'modernizr',
    // },
    // {
    //   fileNames: [
    //     '.nest-cli.json',
    //     '.nestconfig.json',
    //     'nest-cli.json',
    //     'nestconfig.json',
    //   ],
    //   name: 'nest',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['controller.ts', 'controller.js'],
    //   name: 'nest-controller',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['decorator.ts', 'decorator.js'],
    //   name: 'nest-decorator',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['filter.ts', 'filter.js'],
    //   name: 'nest-filter',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['gateway.ts', 'gateway.js'],
    //   name: 'nest-gateway',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['guard.ts', 'guard.js'],
    //   name: 'nest-guard',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['middleware.ts', 'middleware.js'],
    //   name: 'nest-middleware',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['module.ts', 'module.js'],
    //   name: 'nest-module',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['pipe.ts', 'pipe.js'],
    //   name: 'nest-pipe',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['resolver.ts', 'resolver.js'],
    //   name: 'nest-resolver',
    // },
    // {
    //   enabledFor: [IconPack.Nest],
    //   fileExtensions: ['service.ts', 'service.js'],
    //   name: 'nest-service',
    // },
    // {
    //   fileNames: [
    //     'netlify.json',
    //     'netlify.toml',
    //     'netlify.yaml',
    //     'netlify.yml',
    //   ],
    //   name: 'netlify',
    // },
    // {
    //   fileNames: [
    //     'next.config.js',
    //     'next.config.mjs',
    //     'next.config.mts',
    //     'next.config.ts',
    //   ],
    //   light: true,
    //   name: 'next',
    // },
    // {
    //   fileExtensions: ['nginx', 'nginxconfig'],
    //   fileNames: ['nginx.conf'],
    //   name: 'nginx',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileExtensions: ['actions.ts'],
    //   name: 'ngrx-actions',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileExtensions: ['effects.ts'],
    //   name: 'ngrx-effects',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileNames: ['.entity'],
    //   name: 'ngrx-entity',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileExtensions: ['reducer.ts', 'rootReducer.ts'],
    //   name: 'ngrx-reducer',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileExtensions: ['selectors.ts'],
    //   name: 'ngrx-selectors',
    // },
    // {
    //   enabledFor: [IconPack.Ngrx],
    //   fileExtensions: ['state.ts'],
    //   name: 'ngrx-state',
    // },
    // {
    //   fileNames: [
    //     '.esmrc',
    //     '.node-version',
    //     '.nvmrc',
    //     'package-lock.json',
    //     'package.json',
    //   ],
    //   name: 'nodejs',
    // },
    // {
    //   fileExtensions: ['nupkg'],
    //   fileNames: ['nuget.config', '.nuspec', 'nuget.exe'],
    //   name: 'nuget',
    // },
    // {
    //   fileNames: ['nuxt.config.js', 'nuxt.config.ts', '.nuxtignore'],
    //   name: 'nuxt',
    // },
    // {
    //   fileNames: [
    //     '.php-cs-fixer.dist.php',
    //     '.php-cs-fixer.php',
    //     '.php_cs',
    //     '.php_cs.dist',
    //     '.php_cs.dist.php',
    //     '.php_cs.php',
    //   ],
    //   name: 'php-cs-fixer',
    // },
    // {
    //   fileNames: [
    //     '.phpunit-watcher.yml',
    //     '.phpunit.result.cache',
    //     'phpunit-watcher.yml',
    //     'phpunit-watcher.yml.dist',
    //     'phpunit.xml',
    //     'phpunit.xml.dist',
    //   ],
    //   name: 'phpunit',
    // },
    // {
    //   fileNames: [
    //     'playwright-ct.config.js',
    //     'playwright-ct.config.mjs',
    //     'playwright-ct.config.ts',
    //     'playwright.config.js',
    //     'playwright.config.mjs',
    //     'playwright.config.ts',
    //   ],
    //   name: 'playwright',
    // },
    // {
    //   fileNames: ['pnpm-lock.yaml', 'pnpm-workspace.yaml', '.pnpmfile.cjs'],
    //   light: true,
    //   name: 'pnpm',
    // },
    // {
    //   fileExtensions: ['pcss', 'sss'],
    //   fileNames: [
    //     '.postcssrc',
    //     '.postcssrc.cjs',
    //     '.postcssrc.cts',
    //     '.postcssrc.js',
    //     '.postcssrc.json',
    //     '.postcssrc.ts',
    //     '.postcssrc.yaml',
    //     '.postcssrc.yml',
    //     'postcss.config.cjs',
    //     'postcss.config.cts',
    //     'postcss.config.js',
    //     'postcss.config.ts',
    //   ],
    //   name: 'postcss',
    // },
    // {
    //   fileNames: [
    //     '.posthtmlrc',
    //     '.posthtmlrc.js',
    //     '.posthtmlrc.json',
    //     '.posthtmlrc.yml',
    //     'posthtml.config.js',
    //   ],
    //   name: 'posthtml',
    // },
    // {
    //   fileExtensions: [
    //     'odp',
    //     'potm',
    //     'potx',
    //     'ppa',
    //     'ppam',
    //     'pps',
    //     'ppsm',
    //     'ppsx',
    //     'ppt',
    //     'pptm',
    //     'pptx',
    //   ],
    //   name: 'powerpoint',
    // },
    // {
    //   fileExtensions: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
    //   name: 'powershell',
    // },
    // {
    //   fileNames: [
    //     '.prettierignore',
    //     '.prettierrc',
    //     '.prettierrc.cjs',
    //     '.prettierrc.js',
    //     '.prettierrc.json',
    //     '.prettierrc.json5',
    //     '.prettierrc.toml',
    //     '.prettierrc.yaml',
    //     '.prettierrc.yml',
    //     'prettier.config.cjs',
    //     'prettier.config.js',
    //   ],
    //   name: 'prettier',
    // },
    // {
    //   fileNames: [
    //     'protractor.conf.coffee',
    //     'protractor.conf.js',
    //     'protractor.conf.ts',
    //     'protractor.config.js',
    //     'protractor.config.ts',
    //   ],
    //   name: 'protractor',
    // },
    // {
    //   fileExtensions: ['jade', 'pug'],
    //   fileNames: ['.pug-lintrc', '.pug-lintrc.js', '.pug-lintrc.json'],
    //   name: 'pug',
    // },
    // {
    //   fileExtensions: ['pyc', 'whl'],
    //   fileNames: [
    //     '.pylintrc',
    //     '.python-version',
    //     'manifest.in',
    //     'pipfile',
    //     'pylintrc',
    //     'pyproject.toml',
    //     'requirements.txt',
    //   ],
    //   name: 'python-misc',
    // },
    // {
    //   fileNames: ['readme.md', 'readme.rst', 'readme.txt', 'readme'],
    //   name: 'readme',
    // },
    // {
    //   enabledFor: [IconPack.Redux],
    //   fileExtensions: ['action.js', 'actions.js', 'action.ts', 'actions.ts'],
    //   fileNames: ['action.js', 'actions.js', 'action.ts', 'actions.ts'],
    //   name: 'redux-action',
    // },
    // {
    //   enabledFor: [IconPack.Redux],
    //   fileExtensions: [
    //     'reducer.js',
    //     'reducer.ts',
    //     'reducers.js',
    //     'reducers.ts',
    //   ],
    //   fileNames: ['reducer.js', 'reducers.js', 'reducer.ts', 'reducers.ts'],
    //   name: 'redux-reducer',
    // },
    // {
    //   enabledFor: [IconPack.Redux],
    //   fileExtensions: [
    //     'selector.js',
    //     'selector.ts',
    //     'selectors.js',
    //     'selectors.ts',
    //   ],
    //   fileNames: ['selector.js', 'selectors.js', 'selector.ts', 'selectors.ts'],
    //   name: 'redux-selector',
    // },
    // {
    //   enabledFor: [IconPack.Redux],
    //   fileExtensions: ['store.js', 'store.ts'],
    //   fileNames: ['store.js', 'store.ts'],
    //   name: 'redux-store',
    // },
    // {
    //   fileNames: ['remix.config.js', 'remix.config.ts'],
    //   light: true,
    //   name: 'remix',
    // },
    // {
    //   fileNames: [
    //     '.renovaterc',
    //     '.renovaterc.json',
    //     'renovate-config.json',
    //     'renovate.json',
    //     'renovate.json5',
    //   ],
    //   name: 'renovate',
    // },
    // {
    //   fileNames: [
    //     'milestones.md',
    //     'milestones.txt',
    //     'roadmap.md',
    //     'roadmap.txt',
    //     'timeline.md',
    //     'timeline.txt',
    //   ],
    //   name: 'roadmap',
    // },
    // {
    //   fileNames: [
    //     'rollup-config.js',
    //     'rollup-config.ts',
    //     'rollup.config.base.js',
    //     'rollup.config.base.ts',
    //     'rollup.config.common.js',
    //     'rollup.config.common.ts',
    //     'rollup.config.dev.js',
    //     'rollup.config.dev.ts',
    //     'rollup.config.js',
    //     'rollup.config.prod.js',
    //     'rollup.config.prod.ts',
    //     'rollup.config.prod.vendor.js',
    //     'rollup.config.prod.vendor.ts',
    //     'rollup.config.ts',
    //   ],
    //   name: 'rollup',
    // },
    // {
    //   enabledFor: [
    //     IconPack.Angular,
    //     IconPack.Ngrx,
    //     IconPack.React,
    //     IconPack.Redux,
    //     IconPack.Vue,
    //     IconPack.Vuex,
    //   ],
    //   fileExtensions: [
    //     'routes.js',
    //     'routes.jsx',
    //     'routes.ts',
    //     'routes.tsx',
    //     'routing.js',
    //     'routing.jsx',
    //     'routing.ts',
    //     'routing.tsx',
    //   ],
    //   fileNames: [
    //     'router.js',
    //     'router.jsx',
    //     'router.ts',
    //     'router.tsx',
    //     'routes.js',
    //     'routes.jsx',
    //     'routes.ts',
    //     'routes.tsx',
    //   ],
    //   name: 'routing',
    // },
    // {
    //   fileNames: ['.rubocop.yml', '.rubocop-todo.yml', '.rubocop_todo.yml'],
    //   light: true,
    //   name: 'rubocop',
    // },
    // {
    //   fileExtensions: ['sas', 'sas7bdat', 'sashdat', 'astore', 'ast', 'sast'],
    //   name: 'sas',
    // },
    // {
    //   fileNames: [
    //     '.releaserc',
    //     '.releaserc.js',
    //     '.releaserc.json',
    //     '.releaserc.yaml',
    //     '.releaserc.yml',
    //     'release.config.js',
    //   ],
    //   light: true,
    //   name: 'semantic-release',
    // },
    // {
    //   fileExtensions: [
    //     'cfg',
    //     'conf',
    //     'config',
    //     'dlc',
    //     'dll',
    //     'ini',
    //     'option',
    //     'prefs',
    //     'prop',
    //     'properties',
    //     'props',
    //     'settings',
    //     'sln.dotsettings',
    //     'sln.dotsettings.user',
    //     'toml',
    //   ],
    //   fileNames: [
    //     '.buildignore',
    //     '.clang-format',
    //     '.clang-tidy',
    //     '.jshintignore',
    //     '.mrconfig',
    //     '.yardopts',
    //     'manifest.mf',
    //   ],
    //   name: 'settings',
    // },
    // {
    //   fileExtensions: [
    //     'comp',
    //     'comp.glsl',
    //     'comp.hlsl',
    //     'compute.glsl',
    //     'compute.hlsl',
    //     'computeshader',
    //     'frag',
    //     'frag.glsl',
    //     'fragment.glsl',
    //     'fragmentshader',
    //     'fs.glsl',
    //     'geom',
    //     'geom.glsl',
    //     'geom.hlsl',
    //     'geometry.glsl',
    //     'geometry.hlsl',
    //     'geometryshader',
    //     'glsl',
    //     'gs.glsl',
    //     'hlsl',
    //     'pixel.hlsl',
    //     'px.hlsl',
    //     'shader',
    //     'tesc',
    //     'tesc.glsl',
    //     'tese',
    //     'tese.glsl',
    //     'tess.hlsl',
    //     'tessellation.hlsl',
    //     'ts.glsl',
    //     'vert',
    //     'vert.glsl',
    //     'vertex.glsl',
    //     'vertexshader',
    //     'vs.glsl',
    //     'wgsl',
    //   ],
    //   name: 'shader',
    // },
    // {
    //   fileExtensions: [
    //     'cm',
    //     'fun',
    //     'grm',
    //     'lex',
    //     'mlb',
    //     'mlton',
    //     'sig',
    //     'sml',
    //     'use',
    //   ],
    //   name: 'sml',
    // },
    // {
    //   fileNames: [
    //     'snowpack.config.cjs',
    //     'snowpack.config.cts',
    //     'snowpack.config.js',
    //     'snowpack.config.json',
    //     'snowpack.config.mjs',
    //     'snowpack.config.mts',
    //     'snowpack.config.ts',
    //     'snowpack.deps.json',
    //   ],
    //   light: true,
    //   name: 'snowpack',
    // },
    // {
    //   fileExtensions: ['steadybit.yml', 'steadybit.yaml'],
    //   fileNames: [
    //     '.steadybit.yaml',
    //     '.steadybit.yml',
    //     'steadybit.yaml',
    //     'steadybit.yml',
    //   ],
    //   name: 'steadybit',
    // },
    // {
    //   fileNames: ['stitches.config.js', 'stitches.config.ts'],
    //   light: true,
    //   name: 'stitches',
    // },
    // {
    //   fileExtensions: [
    //     'stories.js',
    //     'stories.jsx',
    //     'stories.mdx',
    //     'stories.svelte',
    //     'stories.ts',
    //     'stories.tsx',
    //     'story.js',
    //     'story.jsx',
    //     'story.mdx',
    //     'story.ts',
    //     'story.tsx',
    //   ],
    //   name: 'storybook',
    // },
    // {
    //   fileNames: [
    //     '.stylelintignore',
    //     '.stylelintrc',
    //     '.stylelintrc.cjs',
    //     '.stylelintrc.js',
    //     '.stylelintrc.json',
    //     '.stylelintrc.yaml',
    //     '.stylelintrc.yml',
    //     'stylelint.config.cjs',
    //     'stylelint.config.js',
    //   ],
    //   light: true,
    //   name: 'stylelint',
    // },
    // {
    //   fileExtensions: ['sublime-project', 'sublime-workspace'],
    //   name: 'sublime',
    // },
    // {
    //   fileExtensions: ['svelte'],
    //   fileNames: ['svelte.config.js', 'svelte.config.cjs'],
    //   name: 'svelte',
    // },
    // {
    //   fileNames: [
    //     '.svgrrc',
    //     '.svgrrc.js',
    //     '.svgrrc.json',
    //     '.svgrrc.yaml',
    //     '.svgrrc.yml',
    //     'svgr.config.js',
    //   ],
    //   name: 'svgr',
    // },
    // {
    //   fileExtensions: ['xlsx', 'xlsm', 'xls', 'csv', 'tsv', 'psv', 'ods'],
    //   name: 'table',
    // },
    // {
    //   fileNames: [
    //     'tailwind.config.cjs',
    //     'tailwind.config.cts',
    //     'tailwind.config.js',
    //     'tailwind.config.ts',
    //     'tailwind.js',
    //     'tailwind.ts',
    //   ],
    //   name: 'tailwindcss',
    // },
    // {
    //   fileExtensions: ['tauri'],
    //   fileNames: [
    //     'tauri.conf.json',
    //     'tauri.config.json',
    //     'tauri.linux.conf.json',
    //     'tauri.macos.conf.json',
    //     'tauri.windows.conf.json',
    //   ],
    //   name: 'tauri',
    // },
    // {
    //   fileExtensions: ['tf', 'tf.json', 'tfvars', 'tfstate'],
    //   name: 'terraform',
    // },
    // {
    //   fileExtensions: [
    //     'cy.js',
    //     'e2e-spec.cjs',
    //     'e2e-spec.js',
    //     'e2e-spec.mjs',
    //     'js.snap',
    //     'spec.cjs',
    //     'spec.js',
    //     'spec.mjs',
    //     'test.cjs',
    //     'test.js',
    //     'test.mjs',
    //   ],
    //   name: 'test-js',
    // },
    // {
    //   fileExtensions: [
    //     'cy.jsx',
    //     'cy.tsx',
    //     'jsx.snap',
    //     'spec.jsx',
    //     'spec.tsx',
    //     'test.jsx',
    //     'test.tsx',
    //     'tsx.snap',
    //   ],
    //   name: 'test-jsx',
    // },
    // {
    //   fileExtensions: [
    //     'cy.ts',
    //     'e2e-spec.cts',
    //     'e2e-spec.mts',
    //     'e2e-spec.ts',
    //     'spec.cts',
    //     'spec.mts',
    //     'spec.ts',
    //     'test.cts',
    //     'test.mts',
    //     'test.ts',
    //     'ts.snap',
    //   ],
    //   name: 'test-ts',
    // },
    // {
    //   fileNames: ['.textlintrc'],
    //   name: 'textlint',
    // },
    // {
    //   fileExtensions: ['tsconfig.json'],
    //   fileNames: [
    //     'tsconfig.app.json',
    //     'tsconfig.base.json',
    //     'tsconfig.build.json',
    //     'tsconfig.e2e.json',
    //     'tsconfig.editor.json',
    //     'tsconfig.eslint.json',
    //     'tsconfig.json',
    //     'tsconfig.lib.json',
    //     'tsconfig.node.json',
    //     'tsconfig.spec.json',
    //     'tsconfig.test.json',
    //     'tsconfig.web.json',
    //     'tsconfig.webworker.json',
    //   ],
    //   name: 'tsconfig',
    // },
    // {
    //   fileExtensions: ['env'],
    //   fileNames: [
    //     '.env.alpha',
    //     '.env.defaults',
    //     '.env.dev',
    //     '.env.development',
    //     '.env.development.local',
    //     '.env.dist',
    //     '.env.e2e',
    //     '.env.example',
    //     '.env.local',
    //     '.env.preview',
    //     '.env.prod',
    //     '.env.production',
    //     '.env.production.local',
    //     '.env.qa',
    //     '.env.qa.local',
    //     '.env.sample',
    //     '.env.schema',
    //     '.env.stage',
    //     '.env.staging',
    //     '.env.staging.local',
    //     '.env.template',
    //     '.env.test',
    //     '.env.test.local',
    //     '.env.testing',
    //   ],
    //   name: 'tune',
    // },
    // {
    //   fileNames: ['turbo.json'],
    //   light: true,
    //   name: 'turborepo',
    // },
    // {
    //   fileExtensions: ['d.ts', 'd.cts', 'd.mts'],
    //   name: 'typescript-def',
    // },
    // {
    //   fileExtensions: ['iuml', 'pu', 'puml', 'plantuml', 'wsd'],
    //   light: true,
    //   name: 'uml',
    // },
    // {
    //   fileExtensions: ['vagrantfile'],
    //   fileNames: ['vagrantfile'],
    //   name: 'vagrant',
    // },
    // {
    //   fileNames: ['vercel.json', '.vercelignore', 'now.json', '.nowignore'],
    //   light: true,
    //   name: 'vercel',
    // },
    // {
    //   fileNames: ['verdaccio.yml'],
    //   name: 'verdaccio',
    // },
    // {
    //   fileExtensions: [
    //     'avi',
    //     'flv',
    //     'gifv',
    //     'm2v',
    //     'm4v',
    //     'mkv',
    //     'mov',
    //     'mp2',
    //     'mp4',
    //     'mpe',
    //     'mpeg',
    //     'mpg',
    //     'mpv',
    //     'ogg',
    //     'ogv',
    //     'qt',
    //     'rm',
    //     'rmvb',
    //     'vob',
    //     'webm',
    //     'wmv',
    //     'yuv',
    //   ],
    //   name: 'video',
    // },
    // {
    //   fileExtensions: ['vimrc', 'gvimrc', 'exrc', 'vim', 'viminfo'],
    //   name: 'vim',
    // },
    // {
    //   fileExtensions: [
    //     'csproj',
    //     'ruleset',
    //     'sln',
    //     'suo',
    //     'vb',
    //     'vbs',
    //     'vcxitems',
    //     'vcxitems.filters',
    //     'vcxproj',
    //     'vcxproj.filters',
    //   ],
    //   name: 'visualstudio',
    // },
    // {
    //   fileNames: [
    //     'vite.config.cjs',
    //     'vite.config.cts',
    //     'vite.config.js',
    //     'vite.config.mjs',
    //     'vite.config.mts',
    //     'vite.config.ts',
    //   ],
    //   name: 'vite',
    // },
    // {
    //   fileExtensions: [
    //     'code-workplace',
    //     'vscodeignore',
    //     'vsix',
    //     'vsixmanifest',
    //   ],
    //   name: 'vscode',
    // },
    // {
    //   fileNames: [
    //     'vetur.config.js',
    //     'vetur.config.ts',
    //     'vue.config.js',
    //     'vue.config.ts',
    //   ],
    //   name: 'vue-config',
    // },
    // {
    //   enabledFor: [IconPack.Vuex],
    //   fileExtensions: ['store.js', 'store.ts'],
    //   fileNames: ['store.js', 'store.ts'],
    //   name: 'vuex-store',
    // },
    // {
    //   fileExtensions: ['.wakatime-project'],
    //   fileNames: ['.wakatime-project'],
    //   light: true,
    //   name: 'wakatime',
    // },
    // {
    //   fileNames: [
    //     'webpack.base.cjs',
    //     'webpack.base.cts',
    //     'webpack.base.js',
    //     'webpack.base.mjs',
    //     'webpack.base.mts',
    //     'webpack.base.ts',
    //     'webpack.cjs',
    //     'webpack.client.cjs',
    //     'webpack.client.cts',
    //     'webpack.client.js',
    //     'webpack.client.mjs',
    //     'webpack.client.mts',
    //     'webpack.client.ts',
    //     'webpack.common.cjs',
    //     'webpack.common.cts',
    //     'webpack.common.js',
    //     'webpack.common.mjs',
    //     'webpack.common.mts',
    //     'webpack.common.ts',
    //     'webpack.config.babel.js',
    //     'webpack.config.babel.ts',
    //     'webpack.config.base.babel.js',
    //     'webpack.config.base.babel.ts',
    //     'webpack.config.base.cjs',
    //     'webpack.config.base.cts',
    //     'webpack.config.base.js',
    //     'webpack.config.base.mjs',
    //     'webpack.config.base.mts',
    //     'webpack.config.base.ts',
    //     'webpack.config.cjs',
    //     'webpack.config.client.cjs',
    //     'webpack.config.client.cts',
    //     'webpack.config.client.js',
    //     'webpack.config.client.mjs',
    //     'webpack.config.client.mts',
    //     'webpack.config.client.ts',
    //     'webpack.config.coffee',
    //     'webpack.config.common.babel.js',
    //     'webpack.config.common.babel.ts',
    //     'webpack.config.common.cjs',
    //     'webpack.config.common.cts',
    //     'webpack.config.common.js',
    //     'webpack.config.common.mjs',
    //     'webpack.config.common.mts',
    //     'webpack.config.common.ts',
    //     'webpack.config.cts',
    //     'webpack.config.dev.babel.js',
    //     'webpack.config.dev.babel.ts',
    //     'webpack.config.dev.cjs',
    //     'webpack.config.dev.cts',
    //     'webpack.config.dev.js',
    //     'webpack.config.dev.mjs',
    //     'webpack.config.dev.mts',
    //     'webpack.config.dev.ts',
    //     'webpack.config.js',
    //     'webpack.config.mjs',
    //     'webpack.config.mts',
    //     'webpack.config.prod.babel.cjs',
    //     'webpack.config.prod.babel.cts',
    //     'webpack.config.prod.babel.js',
    //     'webpack.config.prod.babel.mjs',
    //     'webpack.config.prod.babel.mts',
    //     'webpack.config.prod.babel.ts',
    //     'webpack.config.prod.cjs',
    //     'webpack.config.prod.cts',
    //     'webpack.config.prod.js',
    //     'webpack.config.prod.mjs',
    //     'webpack.config.prod.mts',
    //     'webpack.config.prod.ts',
    //     'webpack.config.production.babel.js',
    //     'webpack.config.production.babel.ts',
    //     'webpack.config.production.cjs',
    //     'webpack.config.production.cts',
    //     'webpack.config.production.js',
    //     'webpack.config.production.mjs',
    //     'webpack.config.production.mts',
    //     'webpack.config.production.ts',
    //     'webpack.config.server.cjs',
    //     'webpack.config.server.cts',
    //     'webpack.config.server.js',
    //     'webpack.config.server.mjs',
    //     'webpack.config.server.mts',
    //     'webpack.config.server.ts',
    //     'webpack.config.staging.babel.js',
    //     'webpack.config.staging.babel.ts',
    //     'webpack.config.staging.cjs',
    //     'webpack.config.staging.cts',
    //     'webpack.config.staging.js',
    //     'webpack.config.staging.mjs',
    //     'webpack.config.staging.mts',
    //     'webpack.config.staging.ts',
    //     'webpack.config.test.cjs',
    //     'webpack.config.test.cts',
    //     'webpack.config.test.js',
    //     'webpack.config.test.mjs',
    //     'webpack.config.test.mts',
    //     'webpack.config.test.ts',
    //     'webpack.config.ts',
    //     'webpack.config.vendor.cjs',
    //     'webpack.config.vendor.cts',
    //     'webpack.config.vendor.js',
    //     'webpack.config.vendor.mjs',
    //     'webpack.config.vendor.mts',
    //     'webpack.config.vendor.production.cjs',
    //     'webpack.config.vendor.production.cts',
    //     'webpack.config.vendor.production.js',
    //     'webpack.config.vendor.production.mjs',
    //     'webpack.config.vendor.production.mts',
    //     'webpack.config.vendor.production.ts',
    //     'webpack.config.vendor.ts',
    //     'webpack.cts',
    //     'webpack.dev.cjs',
    //     'webpack.dev.cts',
    //     'webpack.dev.js',
    //     'webpack.dev.mjs',
    //     'webpack.dev.mts',
    //     'webpack.dev.ts',
    //     'webpack.development.cjs',
    //     'webpack.development.cts',
    //     'webpack.development.js',
    //     'webpack.development.mjs',
    //     'webpack.development.mts',
    //     'webpack.development.ts',
    //     'webpack.dist.cjs',
    //     'webpack.dist.cts',
    //     'webpack.dist.js',
    //     'webpack.dist.mjs',
    //     'webpack.dist.mts',
    //     'webpack.dist.ts',
    //     'webpack.js',
    //     'webpack.mix.cjs',
    //     'webpack.mix.cts',
    //     'webpack.mix.js',
    //     'webpack.mix.mjs',
    //     'webpack.mix.mts',
    //     'webpack.mix.ts',
    //     'webpack.mjs',
    //     'webpack.mts',
    //     'webpack.prod.cjs',
    //     'webpack.prod.config.cjs',
    //     'webpack.prod.config.cts',
    //     'webpack.prod.config.js',
    //     'webpack.prod.config.mjs',
    //     'webpack.prod.config.mts',
    //     'webpack.prod.config.ts',
    //     'webpack.prod.cts',
    //     'webpack.prod.js',
    //     'webpack.prod.mjs',
    //     'webpack.prod.mts',
    //     'webpack.prod.ts',
    //     'webpack.production.cjs',
    //     'webpack.production.cts',
    //     'webpack.production.js',
    //     'webpack.production.mjs',
    //     'webpack.production.mts',
    //     'webpack.production.ts',
    //     'webpack.server.cjs',
    //     'webpack.server.cts',
    //     'webpack.server.js',
    //     'webpack.server.mjs',
    //     'webpack.server.mts',
    //     'webpack.server.ts',
    //     'webpack.test.cjs',
    //     'webpack.test.cts',
    //     'webpack.test.js',
    //     'webpack.test.mjs',
    //     'webpack.test.mts',
    //     'webpack.test.ts',
    //     'webpack.ts',
    //     'webpackfile.cjs',
    //     'webpackfile.cts',
    //     'webpackfile.js',
    //     'webpackfile.mjs',
    //     'webpackfile.mts',
    //     'webpackfile.ts',
    //   ],
    //   name: 'webpack',
    // },
    // {
    //   fileExtensions: ['windi'],
    //   fileNames: [
    //     'windi.config.cjs',
    //     'windi.config.cts',
    //     'windi.config.js',
    //     'windi.config.json',
    //     'windi.config.ts',
    //   ],
    //   name: 'windicss',
    // },
    // {
    //   fileExtensions: [
    //     'dmn',
    //     'dtd',
    //     'iml',
    //     'manifest',
    //     'plist',
    //     'project',
    //     'resx',
    //     'tmLanguage',
    //     'xml',
    //     'xml.dist',
    //     'xml.dist.sample',
    //     'xquery',
    //     'xsd',
    //     'xsl',
    //     'xslt',
    //   ],
    //   fileNames: ['.htaccess'],
    //   name: 'xml',
    // },
    // {
    //   fileExtensions: [
    //     'yaml',
    //     'YAML-tmLanguage',
    //     'yaml.dist',
    //     'yml',
    //     'yml.dist',
    //   ],
    //   name: 'yaml',
    // },
    // {
    //   fileNames: [
    //     '.yarn-integrity',
    //     '.yarnclean',
    //     '.yarnrc',
    //     '.yarnrc.yaml',
    //     '.yarnrc.yml',
    //     'yarn-error.log',
    //     'yarn.lock',
    //   ],
    //   name: 'yarn',
    // },
    // {
    //   fileExtensions: [
    //     '7z',
    //     'br',
    //     'brotli',
    //     'bz2',
    //     'bzip2',
    //     'gz',
    //     'gzip',
    //     'lz4',
    //     'lzma',
    //     'rar',
    //     'tar',
    //     'tgz',
    //     'txz',
    //     'tz',
    //     'xz',
    //     'zip',
    //   ],
    //   name: 'zip',
    // },
    // { name: 'abc', fileExtensions: ['abc'] },
    // { name: 'actionscript', fileExtensions: ['as'] },
    // { name: 'ada', fileExtensions: ['ada', 'adb', 'ads', 'ali'] },
    // { name: 'adonis', fileNames: ['.adonisrc.json', 'ace'] },
    // { name: 'advpl_include', fileExtensions: ['ch'] },
    // { name: 'advpl_prw', fileExtensions: ['prw', 'prx'] },
    // { name: 'advpl_ptm', fileExtensions: ['ptm'] },
    // { name: 'advpl_tlpp', fileExtensions: ['tlpp'] },
    // { name: 'apiblueprint', fileExtensions: ['apib', 'apiblueprint'] },
    // { name: 'apollo', fileNames: ['apollo.config.js'] },
    // { name: 'applescript', fileExtensions: ['applescript', 'ipa'] },
    // { name: 'appveyor', fileNames: ['.appveyor.yml', 'appveyor.yml'] },
    // { name: 'arduino', fileExtensions: ['ino'] },
    // { name: 'asciidoc', fileExtensions: ['ad', 'adoc', 'asciidoc'] },
    // { name: 'astyle', fileNames: ['.astylerc'] },
    // { name: 'aurelia', fileNames: ['aurelia.json'] },
    // { name: 'autohotkey', fileExtensions: ['ahk'] },
    // { name: 'autoit', fileExtensions: ['au3'] },
    // { name: 'azure', fileExtensions: ['azcli'] },
    // { name: 'ballerina', fileExtensions: ['bal', 'balx'] },
    // { name: 'bicep', fileExtensions: ['bicep'] },
    // { name: 'bithound', fileNames: ['.bithoundrc'] },
    // { name: 'blink', fileExtensions: ['blink'], light: true },
    // { name: 'bower', fileNames: ['.bowerrc', 'bower.json'] },
    // { name: 'brainfuck', fileExtensions: ['b', 'bf'] },
    // { name: 'buck', fileNames: ['.buckconfig'] },
    // { name: 'bucklescript', fileExtensions: ['cmj'] },
    // { name: 'buildkite', fileNames: ['buildkite.yml', 'buildkite.yaml'] },
    // { name: 'c', fileExtensions: ['c', 'i', 'mi'] },
    // { name: 'cake', fileExtensions: ['cake'] },
    // { name: 'chess', fileExtensions: ['pgn', 'fen'], light: true },
    // { name: 'circleci', fileNames: ['circle.yml'], light: true },
    // { name: 'clojure', fileExtensions: ['clj', 'cljs', 'cljc'] },
    // { name: 'cloudfoundry', fileNames: ['.cfignore'] },
    // { name: 'coala', fileExtensions: ['coarc', 'coafile'] },
    // { name: 'cobol', fileExtensions: ['cob', 'cbl'] },
    // { name: 'coconut', fileExtensions: ['coco'] },
    // { name: 'code-climate', fileNames: ['.codeclimate.yml'], light: true },
    // { name: 'codecov', fileNames: ['.codecov.yml', 'codecov.yml'] },
    // { name: 'codeowners', fileNames: ['codeowners'] },
    // { name: 'coffee', fileExtensions: ['coffee', 'cson', 'iced'] },
    // { name: 'coldfusion', fileExtensions: ['cfml', 'cfc', 'lucee', 'cfm'] },
    // { name: 'command', fileExtensions: ['command'] },
    // { name: 'crystal', fileExtensions: ['cr', 'ecr'], light: true },
    // { name: 'csharp', fileExtensions: ['cs', 'csx'] },
    // { name: 'css', fileExtensions: ['css'] },
    // { name: 'css-map', fileExtensions: ['css.map'] },
    // { name: 'cucumber', fileExtensions: ['feature', 'features'] },
    // { name: 'cuda', fileExtensions: ['cu', 'cuh'] },
    // { name: 'd', fileExtensions: ['d'] },
    // { name: 'dart', fileExtensions: ['dart'], fileNames: ['.pubignore'] },
    // { name: 'dart_generated', fileExtensions: ['freezed.dart', 'g.dart'] },
    // { name: 'denizenscript', fileExtensions: ['dsc'] },
    // { name: 'dependabot', fileNames: ['dependabot.yml'] },
    // { name: 'dhall', fileExtensions: ['dhall', 'dhallb'] },
    // { name: 'disc', fileExtensions: ['iso'] },
    // { name: 'django', fileExtensions: ['djt'] },
    // { name: 'document', fileExtensions: ['txt'] },
    // { name: 'dotjs', fileExtensions: ['def', 'dot', 'jst'] },
    // { name: 'drawio', fileExtensions: ['drawio', 'dio'] },
    // { name: 'edge', fileExtensions: ['edge'] },
    // { name: 'editorconfig', fileNames: ['.editorconfig'] },
    // { name: 'ejs', fileExtensions: ['ejs'] },
    // { name: 'elixir', fileExtensions: ['ex', 'exs', 'eex', 'leex', 'heex'] },
    // { name: 'elm', fileExtensions: ['elm'] },
    // { name: 'email', fileExtensions: ['ics'], fileNames: ['.mailmap'] },
    // { name: 'erlang', fileExtensions: ['erl'] },
    // { name: 'exe', fileExtensions: ['exe', 'msi'] },
    // { name: 'fastlane', fileNames: ['fastfile', 'appfile'] },
    // { name: 'favicon', fileNames: ['favicon.ico'] },
    // { name: 'flash', fileExtensions: ['swf'] },
    // { name: 'flow', fileNames: ['.flowconfig'] },
    // { name: 'forth', fileExtensions: ['4th', 'fth', 'frt'] },
    // { name: 'foxpro', fileExtensions: ['fxp', 'prg'] },
    // { name: 'fsharp', fileExtensions: ['fs', 'fsx', 'fsi', 'fsproj'] },
    // { name: 'fusebox', fileNames: ['fuse.js'] },
    // { name: 'gcp', fileNames: ['.gcloudignore'] },
    // { name: 'gemfile', fileNames: ['gemfile'] },
    // { name: 'gemini', fileExtensions: ['gmi', 'gemini'] },
    // { name: 'gitlab', fileExtensions: ['gitlab-ci.yml'] },
    // { name: 'gitpod', fileNames: ['.gitpod.yml'] },
    // { name: 'gleam', fileNames: ['gleam.toml'], fileExtensions: ['gleam'] },
    // { name: 'go', fileExtensions: ['go'] },
    // { name: 'godot', fileExtensions: ['gd'] },
    // { name: 'godot-assets', fileExtensions: ['godot', 'tres', 'tscn'] },
    // { name: 'grain', fileExtensions: ['gr'] },
    // { name: 'groovy', fileExtensions: ['groovy'] },
    // { name: 'h', fileExtensions: ['h'] },
    // { name: 'hack', fileNames: ['.hhconfig'] },
    // { name: 'haml', fileExtensions: ['haml'] },
    // { name: 'handlebars', fileExtensions: ['hbs', 'mustache'] },
    // { name: 'hardhat', fileNames: ['hardhat.config.js', 'hardhat.config.ts'] },
    // { name: 'haskell', fileExtensions: ['hs'] },
    // { name: 'haxe', fileExtensions: ['hx'] },
    // { name: 'hcl', fileExtensions: ['hcl'], light: true },
    // { name: 'helm', fileNames: ['.helmignore'] },
    // { name: 'heroku', fileNames: ['procfile', 'procfile.windows'] },
    // { name: 'hex', fileExtensions: ['dat', 'bin', 'hex'] },
    // { name: 'html', fileExtensions: ['htm', 'xhtml', 'html_vm', 'asp'] },
    // { name: 'http', fileExtensions: ['http', 'rest'], fileNames: ['CNAME'] },
    // { name: 'i18n', fileExtensions: ['pot', 'po', 'mo', 'lang'] },
    // { name: 'idris', fileExtensions: ['idr', 'ibc'] },
    // { name: 'imba', fileExtensions: ['imba'] },
    // { name: 'ionic', fileNames: ['ionic.config.json', '.io-config.json'] },
    // { name: 'istanbul', fileNames: ['.nycrc', '.nycrc.json'] },
    // { name: 'jar', fileExtensions: ['jar'] },
    // { name: 'java', fileExtensions: ['java', 'jsp'] },
    // { name: 'javaclass', fileExtensions: ['class'] },
    // { name: 'javascript', fileExtensions: ['esx', 'mjs'] },
    // { name: 'julia', fileExtensions: ['jl'] },
    // { name: 'jupyter', fileExtensions: ['ipynb'] },
    // { name: 'kivy', fileExtensions: ['kv'] },
    // { name: 'kl', fileExtensions: ['kl'], fileNames: ['.kl'] },
    // { name: 'kotlin', fileExtensions: ['kt', 'kts'] },
    // { name: 'kusto', fileExtensions: ['kql'] },
    // { name: 'lerna', fileNames: ['lerna.json'] },
    // { name: 'less', fileExtensions: ['less'] },
    // { name: 'lib', fileExtensions: ['lib', 'bib'] },
    // { name: 'lilypond', fileExtensions: ['ly'] },
    // { name: 'liquid', fileExtensions: ['liquid'] },
    // { name: 'lisp', fileExtensions: ['lisp', 'lsp', 'cl', 'fast'] },
    // { name: 'livescript', fileExtensions: ['ls'] },
    // { name: 'log', fileExtensions: ['log'] },
    // { name: 'lolcode', fileExtensions: ['lol'] },
    // { name: 'lua', fileExtensions: ['lua'], fileNames: ['.luacheckrc'] },
    // { name: 'markojs', fileExtensions: ['marko'] },
    // { name: 'mathematica', fileExtensions: ['nb'] },
    // { name: 'mdsvex', fileExtensions: ['svx'] },
    // { name: 'mdx', fileExtensions: ['mdx'] },
    // { name: 'merlin', fileExtensions: ['merlin'] },
    // { name: 'mint', fileExtensions: ['mint'] },
    // { name: 'moonscript', fileExtensions: ['moon'] },
    // { name: 'mxml', fileExtensions: ['mxml'] },
    // { name: 'ndst', fileExtensions: ['ndst.yml', 'ndst.yaml', 'ndst.json'] },
    // { name: 'nim', fileExtensions: ['nim', 'nimble'] },
    // { name: 'nix', fileExtensions: ['nix'] },
    // { name: 'nodemon', fileNames: ['nodemon.json', 'nodemon-debug.json'] },
    // { name: 'npm', fileNames: ['.npmignore', '.npmrc'] },
    // { name: 'nrwl', fileNames: ['nx.json', '.nxignore'] },
    // { name: 'nunjucks', fileExtensions: ['njk', 'nunjucks'] },
    // { name: 'ocaml', fileExtensions: ['ml', 'mli', 'cmx'] },
    // { name: 'odin', fileExtensions: ['odin'] },
    // { name: 'opa', fileExtensions: ['rego'] },
    // { name: 'opam', fileExtensions: ['opam'] },
    // { name: 'otne', fileExtensions: ['otne'] },
    // { name: 'parcel', fileNames: ['.parcelrc'] },
    // { name: 'pascal', fileExtensions: ['pas'] },
    // { name: 'pawn', fileExtensions: ['pwn', 'amx'] },
    // { name: 'pdf', fileExtensions: ['pdf'] },
    // { name: 'percy', fileNames: ['.percy.yml'] },
    // { name: 'perl', fileExtensions: ['pm', 'raku'] },
    // { name: 'pipeline', fileExtensions: ['pipeline'] },
    // { name: 'plop', fileNames: ['plopfile.js', 'plopfile.ts'] },
    // { name: 'poetry', fileNames: ['poetry.lock'] },
    // { name: 'prisma', fileNames: ['prisma.yml'], fileExtensions: ['prisma'] },
    // { name: 'processing', fileExtensions: ['pde'] },
    // { name: 'prolog', fileExtensions: ['p', 'pro', 'pl'] },
    // { name: 'proto', fileExtensions: ['proto'] },
    // { name: 'puppet', fileExtensions: ['pp'] },
    // { name: 'purescript', fileExtensions: ['pure', 'purs'] },
    // { name: 'python', fileExtensions: ['py'] },
    // { name: 'qsharp', fileExtensions: ['qs'] },
    // { name: 'quasar', fileNames: ['quasar.conf.js', 'quasar.config.js'] },
    // { name: 'r', fileExtensions: ['r', 'rmd'], fileNames: ['.Rhistory'] },
    // { name: 'racket', fileExtensions: ['rkt'] },
    // { name: 'raml', fileExtensions: ['raml'] },
    // { name: 'razor', fileExtensions: ['cshtml', 'vbhtml'] },
    // { name: 'react', fileExtensions: ['jsx'] },
    // { name: 'react_ts', fileExtensions: ['tsx'] },
    // { name: 'reason', fileExtensions: ['re', 'rei'] },
    // { name: 'red', fileExtensions: ['red'] },
    // { name: 'replit', fileNames: ['.replit'] },
    // { name: 'rescript', fileExtensions: ['res'] },
    // { name: 'rescript-interface', fileExtensions: ['resi'] },
    // { name: 'restql', fileExtensions: ['rql', 'restql'] },
    // { name: 'riot', fileExtensions: ['riot', 'tag'] },
    // { name: 'robot', fileExtensions: ['robot'] },
    // { name: 'robots', fileNames: ['robots.txt'] },
    // { name: 'rome', fileNames: ['rome.json'] },
    // { name: 'ruby', fileExtensions: ['rb', 'erb'] },
    // { name: 'rust', fileExtensions: ['rs', 'ron'] },
    // { name: 'san', fileExtensions: ['san'] },
    // { name: 'sass', fileExtensions: ['scss', 'sass'] },
    // { name: 'sbt', fileExtensions: ['sbt'] },
    // { name: 'scala', fileExtensions: ['scala', 'sc'] },
    // { name: 'scheme', fileExtensions: ['ss', 'scm'] },
    // { name: 'search', fileExtensions: ['code-search'] },
    // { name: 'sentry', fileNames: ['.sentryclirc'] },
    // { name: 'sequelize', fileNames: ['.sequelizerc'] },
    // { name: 'serverless', fileNames: ['serverless.yml'] },
    // { name: 'shaderlab', fileExtensions: ['unity'] },
    // { name: 'siyuan', fileExtensions: ['sy'] },
    // { name: 'sketch', fileExtensions: ['sketch'] },
    // { name: 'slim', fileExtensions: ['slim'] },
    // { name: 'slug', fileNames: ['.slugignore'] },
    // { name: 'smarty', fileExtensions: ['tpl'] },
    // { name: 'snyk', fileNames: ['.snyk'] },
    // { name: 'solidity', fileExtensions: ['sol'] },
    // { name: 'stencil', fileNames: ['stencil.config.js', 'stencil.config.ts'] },
    // { name: 'stryker', fileNames: ['stryker.conf.js', 'stryker.conf.json'] },
    // { name: 'stylus', fileExtensions: ['styl'] },
    // { name: 'svg', fileExtensions: ['svg'] },
    // { name: 'svgo', fileNames: ['svgo.config.js'] },
    // { name: 'swc', fileExtensions: ['swc'] },
    // { name: 'swift', fileExtensions: ['swift'] },
    // { name: 'tcl', fileExtensions: ['tcl'] },
    // { name: 'teal', fileExtensions: ['tl'] },
    // { name: 'template', fileExtensions: ['template'] },
    // { name: 'tex', fileExtensions: ['tex', 'sty', 'dtx', 'ltx'] },
    // { name: 'tilt', fileNames: ['tiltfile'] },
    // { name: 'tobi', fileExtensions: ['tobi'] },
    // { name: 'tobimake', fileNames: ['.tobimake'] },
    // { name: 'todo', fileExtensions: ['todo'] },
    // { name: 'travis', fileNames: ['.travis.yml'] },
    // { name: 'tree', fileExtensions: ['tree'] },
    // { name: 'twig', fileExtensions: ['twig'] },
    // { name: 'twine', fileExtensions: ['tw', 'twee'] },
    // { name: 'url', fileExtensions: ['url'] },
    // { name: 'vala', fileExtensions: ['vala'] },
    // { name: 'velocity', fileExtensions: ['vm', 'fhtml', 'vtl'] },
    // { name: 'verilog', fileExtensions: ['vhd', 'sv', 'svh'] },
    // { name: 'vfl', fileExtensions: ['vfl'], fileNames: ['.vfl'] },
    // { name: 'virtual', fileExtensions: ['vdi', 'vbox', 'vbox-prev'] },
    // { name: 'vlang', fileExtensions: ['v'], fileNames: ['vpkg.json', 'v.mod'] },
    // { name: 'vue', fileExtensions: ['vue'] },
    // { name: 'wallaby', fileNames: ['wallaby.js', 'wallaby.conf.js'] },
    // { name: 'watchman', fileNames: ['.watchmanconfig'] },
    // { name: 'webassembly', fileExtensions: ['wat', 'wasm'] },
    // { name: 'webhint', fileNames: ['.hintrc'] },
    // { name: 'wepy', fileExtensions: ['wpy'] },
    // { name: 'wolframlanguage', fileExtensions: ['wl', 'wls'] },
    // { name: 'word', fileExtensions: ['doc', 'docx', 'rtf', 'odt'] },
    // { name: 'xaml', fileExtensions: ['xaml'] },
    // { name: 'yang', fileExtensions: ['yang'] },
    // { name: 'zig', fileExtensions: ['zig'] },
  ],
};
