import type { LanguageAssociation } from 'src/@types/associations';

/**
 * Defines icons for language ids
 */
export const languageIcons: LanguageAssociation[] = [
  // {
  //   icon: { name: 'settings' },
  //   ids: ['makefile', 'toml', 'ini', 'properties'],
  // },
  // {
  //   icon: { name: 'twine' },
  //   ids: ['twee3', 'twee3-harlowe-3', 'twee3-chapbook-1', 'twee3-sugarcube-2'],
  // },
  // { icon: { name: 'angular' }, ids: ['ng-template'] },
  // { icon: { name: 'apiblueprint' }, ids: ['apiblueprint'] },
  // { icon: { name: 'applescript' }, ids: ['applescript'] },
  // { icon: { name: 'autoit' }, ids: ['autoit'] },
  // { icon: { name: 'blink' }, ids: ['blink'] },
  // { icon: { name: 'c' }, ids: ['c', 'objective-c', 'objective-cpp'] },
  // { icon: { name: 'cabal' }, ids: ['cabal'] },
  // { icon: { name: 'cake' }, ids: ['cake'] },
  // { icon: { name: 'chess' }, ids: ['pgn'] },
  // { icon: { name: 'clojure' }, ids: ['clojure'] },
  // { icon: { name: 'coffee' }, ids: ['coffeescript'] },
  // { icon: { name: 'coldfusion' }, ids: ['lang-cfml'] },
  // { icon: { name: 'console' }, ids: ['bat', 'awk', 'shellscript'] },
  // { icon: { name: 'cpp' }, ids: ['cpp'] },
  // { icon: { name: 'csharp' }, ids: ['csharp'] },
  // { icon: { name: 'css' }, ids: ['css'] },
  // { icon: { name: 'cucumber' }, ids: ['cucumber'] },
  // { icon: { name: 'dart' }, ids: ['dart'] },
  // { icon: { name: 'database' }, ids: ['sql'] },
  // { icon: { name: 'dhall' }, ids: ['dhall'] },
  // { icon: { name: 'diff' }, ids: ['diff'] },
  // { icon: { name: 'django' }, ids: ['django-html', 'django-txt'] },
  // { icon: { name: 'docker' }, ids: ['dockerfile'] },
  // { icon: { name: 'document' }, ids: ['plaintext'] },
  // { icon: { name: 'editorconfig' }, ids: ['editorconfig'] },
  // { icon: { name: 'elixir' }, ids: ['elixir'] },
  // { icon: { name: 'elm' }, ids: ['elm'] },
  // { icon: { name: 'erlang' }, ids: ['erlang'] },
  // { icon: { name: 'fsharp' }, ids: ['fsharp'] },
  // { icon: { name: 'gemini' }, ids: ['gemini', 'text-gemini'] },
  // { icon: { name: 'git' }, ids: ['git', 'git-commit', 'git-rebase', 'ignore'] },
  // { icon: { name: 'go' }, ids: ['go'] },
  // { icon: { name: 'go_gopher' }, ids: [] },
  // { icon: { name: 'godot' }, ids: ['gdscript'] },
  // { icon: { name: 'grain' }, ids: ['grain'] },
  // { icon: { name: 'graphql' }, ids: ['graphql'] },
  // { icon: { name: 'groovy' }, ids: ['groovy'] },
  // { icon: { name: 'hack' }, ids: ['hack'] },
  // { icon: { name: 'haml' }, ids: ['haml'] },
  // { icon: { name: 'handlebars' }, ids: ['handlebars'] },
  // { icon: { name: 'haskell' }, ids: ['haskell'] },
  // { icon: { name: 'haxe' }, ids: ['haxe', 'hxml'] },
  // { icon: { name: 'hcl' }, ids: ['hcl'] },
  // { icon: { name: 'html' }, ids: ['html'] },
  // { icon: { name: 'idris' }, ids: ['idris'] },
  // { icon: { name: 'java' }, ids: ['java'] },
  // { icon: { name: 'javascript' }, ids: ['javascript'] },
  // { icon: { name: 'jinja' }, ids: ['jinja'] },
  // { icon: { name: 'json' }, ids: ['json', 'jsonc', 'json5'] },
  // { icon: { name: 'julia' }, ids: ['julia'] },
  // { icon: { name: 'jupyter' }, ids: ['jupyter'] },
  // { icon: { name: 'kusto' }, ids: ['kql'] },
  // { icon: { name: 'less' }, ids: ['less'] },
  // { icon: { name: 'lib' }, ids: ['bibtex', 'bibtex-style'] },
  // { icon: { name: 'livescript' }, ids: ['livescript'] },
  // { icon: { name: 'lock' }, ids: ['ssh_config'] },
  // { icon: { name: 'log' }, ids: ['log'] },
  // { icon: { name: 'lolcode' }, ids: ['lolcode'] },
  // { icon: { name: 'lua' }, ids: ['lua'] },
  // { icon: { name: 'markdown' }, ids: ['markdown'] },
  // { icon: { name: 'matlab' }, ids: ['matlab'] },
  // { icon: { name: 'minecraft' }, ids: ['mcfunction'] },
  // { icon: { name: 'mjml' }, ids: ['mjml'] },
  // { icon: { name: 'nim' }, ids: ['nim', 'nimble'] },
  // { icon: { name: 'nix' }, ids: ['nix'] },
  // { icon: { name: 'nodejs_alt' }, ids: [] },
  // { icon: { name: 'nunjucks' }, ids: ['nunjucks'] },
  // { icon: { name: 'otne' }, ids: ['otne'] },
  // { icon: { name: 'pawn' }, ids: ['pawn'] },
  // { icon: { name: 'pdf' }, ids: ['pdf'] },
  // { icon: { name: 'perl' }, ids: ['perl', 'perl6'] },
  // { icon: { name: 'php' }, ids: ['php'] },
  // { icon: { name: 'php_elephant' }, ids: [] },
  // { icon: { name: 'php_elephant_pink' }, ids: [] },
  // { icon: { name: 'postcss' }, ids: ['postcss'] },
  // { icon: { name: 'powershell' }, ids: ['powershell'] },
  // { icon: { name: 'processing' }, ids: ['processing'] },
  // { icon: { name: 'prolog' }, ids: ['prolog'] },
  // { icon: { name: 'proto' }, ids: ['proto'] },
  // { icon: { name: 'pug' }, ids: ['jade'] },
  // { icon: { name: 'pug' }, ids: ['pug'] },
  // { icon: { name: 'puppet' }, ids: ['puppet'] },
  // { icon: { name: 'purescript' }, ids: ['purescript'] },
  // { icon: { name: 'python' }, ids: ['python'] },
  // { icon: { name: 'python-misc' }, ids: ['pip-requirements'] },
  // { icon: { name: 'r' }, ids: ['r', 'rsweave'] },
  // { icon: { name: 'razor' }, ids: ['razor', 'aspnetcorerazor'] },
  // { icon: { name: 'react' }, ids: ['javascriptreact'] },
  // { icon: { name: 'react_ts' }, ids: ['typescriptreact'] },
  // { icon: { name: 'reason' }, ids: ['reason', 'reason_lisp'] },
  // { icon: { name: 'rescript' }, ids: ['rescript'] },
  // { icon: { name: 'riot' }, ids: ['riot'] },
  // { icon: { name: 'robot' }, ids: ['robotframework'] },
  // { icon: { name: 'ruby' }, ids: ['ruby'] },
  // { icon: { name: 'rust' }, ids: ['rust'] },
  // { icon: { name: 'salesforce' }, ids: ['apex'] },
  // { icon: { name: 'sas' }, ids: ['sas'] },
  // { icon: { name: 'sass' }, ids: ['sass', 'scss'] },
  // { icon: { name: 'scala' }, ids: ['scala'] },
  // { icon: { name: 'search' }, ids: ['search-result'] },
  // { icon: { name: 'shader' }, ids: ['hlsl', 'glsl', 'wgsl'] },
  // { icon: { name: 'shell' }, ids: ['sh', 'fish', 'bash'] },
  // { icon: { name: 'shaderlab' }, ids: ['shaderlab'] },
  // { icon: { name: 'silverstripe' }, ids: ['ss'] },
  // { icon: { name: 'slim' }, ids: ['slim'] },
  // { icon: { name: 'sml' }, ids: ['sml'] },
  // { icon: { name: 'solidity' }, ids: ['solidity'] },
  // { icon: { name: 'stylus' }, ids: ['stylus'] },
  // { icon: { name: 'svelte' }, ids: ['svelte'] },
  // { icon: { name: 'svg' }, ids: ['svg'] },
  // { icon: { name: 'swift' }, ids: ['swift'] },
  // { icon: { name: 'table' }, ids: ['csv', 'tsv', 'psv'] },
  // { icon: { name: 'terraform' }, ids: ['terraform'] },
  // { icon: { name: 'tex' }, ids: ['tex', 'doctex', 'latex', 'latex-expl3'] },
  // { icon: { name: 'tree' }, ids: ['tree'] },
  // { icon: { name: 'twig' }, ids: ['twig'] },
  // { icon: { name: 'typescript' }, ids: ['typescript'] },
  // { icon: { name: 'vim' }, ids: ['viml'] },
  // { icon: { name: 'visualstudio' }, ids: ['testOutput', 'vb'] },
  // { icon: { name: 'vlang' }, ids: ['v'] },
  // { icon: { name: 'vue' }, ids: ['vue', 'vue-postcss', 'vue-html'] },
  // { icon: { name: 'wolframlanguage' }, ids: ['wolfram'] },
  // { icon: { name: 'xml' }, ids: ['xml', 'xquery', 'xsl'] },
  // { icon: { name: 'yaml' }, ids: ['yaml'] },
  // { icon: { name: 'yang' }, ids: ['yang'] },
];
