export const iFolders = [
  {
    folderNames: [
      'g11n',
      'i18n',
      'l10n',
      'lang',
      'langs',
      'language',
      'languages',
      'locale',
      'locales',
      'localization',
      'translation',
      'translations',
    ],
    name: 'i18n',
  },
  {
    folderNames: [
      'favicon',
      'favicons',
      'glyph',
      'glyphs',
      'icns',
      'ico',
      'icon',
      'icons',
    ],
    name: 'icons',
  },
  {
    folderNames: ['idea', 'META-INF'],
    name: 'idea',
  },
  {
    folderNames: [
      'figure',
      'figures',
      'gallery',
      'image',
      'images',
      'img',
      'imgs',
      'media',
      'medias',
      'pic',
      'pics',
      'picture',
      'pictures',
    ],
    name: 'images',
  },
  {
    folderNames: [
      'concern',
      'concerns',
      'dep',
      'dependencies',
      'dependency',
      'deps',
      'import',
      'imported',
      'imports',
      'inc',
      'include',
      'included',
      'includes',
      'input',
      'inputs',
    ],
    name: 'include',
  },
  {
    folderNames: ['info', 'infos', 'information', 'informations'],
    name: 'info',
  },
  {
    folderNames: [
      'init',
      'initialization',
      'initializer',
      'initializers',
      'startup',
    ],
    name: 'init',
  },
  {
    folderNames: [
      'di',
      'inject',
      'injection',
      'injections',
      'injector',
      'injectors',
      'injects',
    ],
    name: 'injection',
  },
  {
    folderNames: ['istanbul', 'nyc', 'nyc_output', 'nyc-output'],
    name: 'istanbul',
  },
  {
    folderNames: ['lproj', 'xcassets'],
    name: 'ios',
  },
  {
    folderNames: ['ios', 'iosapp', 'ios-app'],
    name: 'iosapp',
  },
];
