export const mFolders = [
  {
    folderNames: ['main', 'mainapp', 'main-app'],
    name: 'main',
  },
  {
    folderNames: [
      'email',
      'emails',
      'mail',
      'mailer',
      'mailers',
      'mailing',
      'mailings',
      'mails',
    ],
    name: 'mailers',
  },
  {
    folderNames: ['markdown', 'md', 'mdown', 'mdx'],
    name: 'markdown',
  },
  {
    folderNames: [
      'algo',
      'algorithm',
      'algorithms',
      'algos',
      'computation',
      'computations',
      'compute',
      'computes',
      'formula',
      'formulas',
      'logic',
      'math',
      'mathjax',
      'maths',
      'scilab',
      'wolfram',
    ],
    name: 'math',
  },
  {
    folderNames: ['maven', 'mvn', 'pom'],
    name: 'maven',
  },
  {
    folderNames: [
      'map',
      'maps',
      'mapping',
      'mappings',
      'mapper',
      'mappers',
    ],
    name: 'maps',
  },
  {
    folderNames: [
      'appex',
      'ccl',
      'ideplugin',
      'kext',
      'mdimporter',
      'osax',
      'osirixplugin',
      'qlgenerator',
    ],
    name: 'osx',
  },
  {
    folderNames: ['mac', 'macos', 'osx'],
    name: 'mac',
  },
  {
    folderNames: [
      'chat',
      'chatroom',
      'chatrooms',
      'chats',
      'comment',
      'comments',
      'forum',
      'forums',
      'message',
      'messages',
      'messaging',
      'msg',
      'msgs',
      'thread',
      'threads',
    ],
    name: 'messages',
  },
  {
    folderNames: ['hg', 'mercurial'],
    name: 'mercurial',
  },
  {
    folderNames: ['meta', 'metadata', 'metas', 'input', 'inputs', 'form', 'forms'],
    name: 'meta',
  },
  {
    folderNames: ['meteor'],
    name: 'meteor',
  },
  {
    folderNames: ['middleware', 'middlewares', 'thunk', 'thunks'],
    name: 'middleware',
  },
  {
    folderNames: ['mindsdb'],
    name: 'mindsdb',
  },
  {
    folderNames: ['mjml'],
    name: 'mjml',
  },
  {
    folderNames: ['mobile', 'mobiles', 'portable', 'portables'],
    name: 'mobile',
  },
  {
    folderNames: [
      'fake',
      'fakes',
      'mock',
      'mocks',
      'mockup',
      'mockups',
      'sketch',
      'sketches',
      'stub',
      'stubs',
      'wireframe',
      'wireframes',
    ],
    name: 'mocks',
  },
  {
    folderNames: [
      'dialog',
      'dialogs',
      'modal',
      'modals',
      'popup',
      'popups',
      'usecase',
      'usecases',
      'dialogbox',
      'dialogboxes',
    ],
    name: 'modals',
  },
  {
    folderNames: [
      'class',
      'classes',
      'dto',
      'entities',
      'entity',
      'model',
      'models',
      'object',
      'objects',
      'struct',
      'structs',
    ],
    name: 'models',
  },
  {
    folderNames: ['molecule', 'molecules'],
    name: 'molecules',
  },
  {
    folderNames: ['mongo', 'mongodb', 'mongoid', 'mongoose'],
    name: 'mongo',
  },
  {
    folderNames: ['moon', 'moonscript'],
    name: 'moon',
  },
  {
    folderNames: ['msw'],
    name: 'msw',
  },
];
