export const tFolders = [
  {
    folderNames: ['target', 'targets'],
    name: 'target',
  },
  {
    folderNames: [
      'cli',
      'cmd',
      'command',
      'commands',
      'console',
      'consoles',
      'run',
      'task',
      'tasks',
      'terminal',
      'ticket',
      'tickets',
      'workflow',
      'workflows',
    ],
    name: 'tasks',
  },
  {
    folderNames: ['taskfile', 'taskfiles'],
    name: 'taskfile',
  },
  {
    folderNames: ['tauri', 'src-tauri'],
    name: 'tauri',
  },
  {
    folderNames: ['tech', 'technologies', 'technology'],
    name: 'tech',
  },
  {
    folderNames: [
      'cache',
      'caches',
      'temp',
      'temporary',
      'temps',
      'tmp',
      'tmps',
    ],
    name: 'temp',
  },
  {
    folderNames: [
      '__tests__',
      'junit',
      'phpunit',
      'pytest',
      'rspec',
      'spec',
      'specs',
      'test',
      'testcase',
      'testcases',
      'tests',
      'unit',
      'units',
    ],
    name: 'tests',
  },
  {
    folderNames: [
      'hcl',
      'terraform',
      'terragrunt',
      'tf',
      'tfstate',
      'tfvars',
    ],
    name: 'terraform',
  },
  {
    folderNames: ['textmate', 'tmbundle'],
    name: 'textmate',
  },
  {
    folderNames: ['trait', 'traits'],
    name: 'trait',
  },
  {
    folderNames: [
      'color',
      'colors',
      'design',
      'designs',
      'palette',
      'palettes',
      'scheme',
      'schemes',
      'skin',
      'skins',
      'theme',
      'themes',
    ],
    name: 'themes',
  },
  {
    folderNames: [
      '@types',
      'interface',
      'interfaces',
      'ts',
      'tsconfig',
      'type',
      'types',
      'typescript',
      'typings',
    ],
    name: 'ts',
  },
];
