export const uFolders = [
  {
    folderNames: ['unity', 'unity3d'],
    name: 'unity',
  },
  {
    folderNames: [
      'update',
      'updated',
      'updates',
      'upgrade',
      'upgraded',
      'upgrades',
      'upload',
      'uploaded',
      'uploads',
    ],
    name: 'upload',
  },
  {
    folderNames: [
      'account',
      'accounts',
      'contact',
      'contacts',
      'friend',
      'friends',
      'member',
      'members',
      'partner',
      'partners',
      'profile',
      'profiles',
      'role',
      'roles',
      'user',
      'users',
    ],
    name: 'users',
  },
  {
    folderNames: [
      'tool',
      'toolbox',
      'toolboxes',
      'toolkit',
      'toolkits',
      'tools',
      'util',
      'utilities',
      'utility',
      'utils',
    ],
    name: 'tools',
  },
];
