export const uFolders = [
  {
    folderNames: ['ui', 'gui', 'ux', 'figma'],
    name: 'ui',
  },
  {
    folderNames: ['unity', 'unity3d'],
    name: 'unity',
  },
  {
    folderNames: [
      'update',
      'updated',
      'updates',
      'upgrade',
      'upgraded',
      'upgrades',
      'upload',
      'uploaded',
      'uploads',
    ],
    name: 'upload',
  },
  {
    folderNames: [
      'account',
      'accounts',
      'contact',
      'contacts',
      'friend',
      'friends',
      'member',
      'members',
      'partner',
      'partners',
      'profile',
      'profiles',
      'role',
      'roles',
      'user',
      'users',
    ],
    name: 'users',
  },
];
