export const config = [
  {
    fileExtensions: ['env', 'env.dev', 'env.prod', 'env.test', 'ini', 'kys', 'ld', 'ldif', 'lds', 'mcf'],
    fileNames: [
      'config.json',
      'config.txt',
      'config.yaml',
      'config.yml',
      'config/json',
      'config/yaml',
      'config/yml',
      'configs.json',
      'configs.txt',
      'configs.yaml',
      'configs.yml',
      'configs/json',
      'configs/yaml',
      'configs/yml',
      'option.json',
      'option.txt',
      'option.yaml',
      'option.yml',
      'option/json',
      'option/yaml',
      'option/yml',
      'options.json',
      'options.txt',
      'options.yaml',
      'options.yml',
      'options/json',
      'options/yaml',
      'options/yml',
      'pref.json',
      'pref.txt',
      'pref.yaml',
      'pref.yml',
      'pref/json',
      'pref/yaml',
      'pref/yml',
      'prefs.json',
      'prefs.txt',
      'prefs.yaml',
      'prefs.yml',
      'prefs/json',
      'prefs/yaml',
      'prefs/yml',
      'setting.json',
      'setting.txt',
      'setting.yaml',
      'setting.yml',
      'setting/json',
      'setting/yaml',
      'setting/yml',
      'settings.json',
      'settings.txt',
      'settings.yaml',
      'settings.yml',
      'settings/json',
      'settings/yaml',
      'settings/yml',
    ],
    name: 'preferences',
  },
  {
    fileExtensions: ['cfg', 'cnf', 'conf', 'config', 'pref', 'prefs'],
    fileNames: ['cnf', 'conf', 'config', 'pref', 'prefs'],
    light: true,
    name: 'config',
  },
  {
    fileExtensions: ['git', 'git-submodules', 'gitattributes', 'gitkeep', 'gitmodules', 'gitrc', 'keep', 'lfsconfig'],
    name: 'git',
  },
];
