export const iFiles = [
  {
    fileExtensions: ['po', 'pot', 'strings'],
    name: 'i18n',
  },
  {
    fileExtensions: [
      'nls.es.json',
      'nls.de.json',
      'nls.json',
      'nls.fr.json',
      'nls.it.json',
      'nls.ja.json',
      'nls.nl.json',
      'nls.ko.json',
      'nls.pt-br.json',
      'nls.pt-pt.json',
      'nls.ru.json',
      'nls.zh-cn.json',
      'nls.zh-tw.json',
    ],
    name: 'i18nlang',
  },
  {
    fileExtensions: [
      'i18n/js',
      'i18n/jsx',
      'i18n/cjs',
      'i18n/mjs',
      'i18n/json',
      'i18n/md',
      'i18n/rst',
      'i18n/ts',
      'i18n/tsx',
      'i18n/yaml',
      'i18n/yml',
      'lang/js',
      'lang/jsx',
      'lang/cjs',
      'lang/mjs',
      'lang/json',
      'lang/md',
      'lang/rst',
      'lang/ts',
      'lang/tsx',
      'lang/yaml',
      'lang/yml',
      'locale/js',
      'locale/jsx',
      'locale/cjs',
      'locale/mjs',
      'locale/json',
      'locale/md',
      'locale/rst',
      'locale/ts',
      'locale/tsx',
      'locale/yaml',
      'locale/yml',
      'locales/js',
      'locales/cjs',
      'locales/mjs',
      'locales/jsx',
      'locales/json',
      'locales/md',
      'locales/rst',
      'locales/ts',
      'locales/tsx',
      'locales/yaml',
      'locales/yml',
      'translation/js',
      'translation/mjs',
      'translation/cjs',
      'translation/jsx',
      'translation/json',
      'translation/md',
      'translation/rst',
      'translation/ts',
      'translation/tsx',
      'translation/yaml',
      'translation/yml',
      'translations/js',
      'translations/cjs',
      'translations/mjs',
      'translations/jsx',
      'translations/json',
      'translations/md',
      'translations/rst',
      'translations/ts',
      'translations/tsx',
      'translations/yaml',
      'translations/yml',
    ],
    name: 'i18nlangfiles',
  },
  {
    fileExtensions: ['icl'],
    name: 'icl',
  },
  {
    fileNames: ['icomoon.json', 'icomoon.dev.json', 'icomoon.prod.json'],
    name: 'icomoon',
  },
  {
    fileExtensions: ['icu', 'nrm'],
    name: 'icu',
  },
  {
    fileExtensions: ['icls', 'iml'],
    name: 'idea',
  },
  {
    fileExtensions: ['ibc', 'idr', 'idris', 'ipkg', 'lidr'],
    name: 'idris',
  },
  {
    fileExtensions: ['dlm', 'idl'],
    name: 'idl',
  },
  {
    fileExtensions: ['ipf'],
    name: 'igor',
  },
  {
    fileExtensions: ['imba', 'imba2'],
    name: 'imba',
  },
  {
    fileExtensions: ['imgbotconfig'],
    name: 'imgbot',
  },
  {
    fileExtensions: ['4gl'],
    name: 'informix',
  },
  {
    fileNames: ['__init__.py'],
    name: 'indexpy',
  },
  {
    fileExtensions: ['infopathxml', 'xsf', 'xsn', 'xtp2'],
    name: 'infopath',
  },
  {
    fileExtensions: ['i7x', 'ni'],
    name: 'inform',
  },
  {
    fileExtensions: ['ink', 'ink2'],
    name: 'ink',
  },
  {
    fileExtensions: ['inx'],
    light: true,
    name: 'inkscape',
  },
  {
    fileExtensions: ['isl', 'iss'],
    name: 'inno',
  },
  {
    fileExtensions: ['img', 'iso', 'nrg', 'udf'],
    name: 'iso',
  },
  {
    fileExtensions: ['nycrc', 'nycrc.json', 'nycrc.yaml', 'nycrc.yml'],
    name: 'istanbul',
  },
  {
    fileNames: [
      'nyc.config.cjs',
      'nyc.config.js',
      'nyc.config.json',
      'nyc.config.mjs',
      'nyc.config.ts',
      'nyc.config.yaml',
      'nyc.config.yml',
    ],
    name: 'istanbulconf',
  },
  {
    fileExtensions: ['io'],
    name: 'io',
  },
  {
    fileExtensions: ['iodine'],
    name: 'iodine',
  },
  {
    fileExtensions: ['ik'],
    name: 'ioke',
  },
  {
    fileNames: [
      'ionic.config',
      'ionic.config.js',
      'ionic.config.json',
      'ionic.project',
      'ionic.project.js',
      'ionic.project.json',
    ],
    name: 'ionic',
  },
  {
    fileExtensions: ['thy'],
    light: true,
    name: 'isabelle',
  },
];
