export const images = [
  {
    fileExtensions: ['jpg', 'jpeg'],
    name: 'jpg',
  },
  {
    fileExtensions: ['gif', 'gifv'],
    name: 'gif',
  },
  {
    fileExtensions: ['png', 'apng'],
    name: 'png',
  },
  {
    fileExtensions: ['cur', 'icns', 'ico', 'icon', 'iconpackage'],
    name: 'icon',
  },
  {
    fileExtensions: ['bmp', 'jbmp', 'wbmp'],
    name: 'bmp',
  },
  {
    fileExtensions: [
      'bpg',
      'dcm',
      'djvu',
      'dpx',
      'ecw',
      'hdp',
      'hdr',
      'heic',
      'heif',
      'iff',
      'jng',
      'jps',
      'jxr',
      'pcx',
      'pict',
      'pxb',
      'pxg',
      'pxm',
      'pxr',
      'pxs',
      'raw',
      'sgi',
      'tga',
      'tiff',
      'vsdm',
      'wbm',
    ],
    name: 'image',
  },
  {
    fileExtensions: ['svg', 'svgz'],
    light: true,
    name: 'svg',
  },
  {
    fileExtensions: ['webp'],
    name: 'webp',
  },
];
