export const kFiles = [
  {
    fileExtensions: ['ksy'],
    name: 'kaitai',
  },
  {
    fileNames: [
      'karma.conf.cjs',
      'karma.conf.coffee',
      'karma.conf.js',
      'karma.conf.mjs',
      'karma.conf.ts',
      'karma.config.cjs',
      'karma.config.coffee',
      'karma.config.js',
      'karma.config.mjs',
      'karma.config.ts',
    ],
    light: true,
    name: 'karma',
  },
  {
    fileExtensions: ['k', 'kdb', 'q', 'quke'],
    name: 'kx',
  },
  {
    fileNames: [
      'kdu.config.js',
      'kdu.config.cjs',
      'kdu.config.mjs',
      'kdu.config.ts',
      'kocan.config.js',
      'kocan.config.cjs',
      'kocan.config.mjs',
      'kocan.config.ts',
    ],
    name: 'kdu',
  },
  {
    fileExtensions: ['ks'],
    name: 'kerboscript',
  },
  {
    fileNames: ['keybase.txt'],
    name: 'keybase',
  },
  {
    fileExtensions: ['knt', 'keynote'],
    name: 'keynote',
  },
  {
    fileExtensions: ['der', 'enc', 'gpg', 'kdbx', 'key', 'passwd', 'pem', 'ssh'],
    name: 'key',
  },
  {
    fileExtensions: ['k'],
    fileNames: ['kcl.mod', 'kcl.yml', 'kcl.yaml'],
    name: 'kcl',
  },
  {
    fileNames: ['publishToken', 'publishToken.md', 'publishToken.txt', 'publishToken.xml'],
    name: 'publishToken',
  },
  {
    fileExtensions: ['kibo'],
    name: 'kibo',
  },
  {
    fileExtensions: ['kicad_mod', 'kicad_pcb', 'kicad_pcb-bak', 'kicad_sch', 'kicad_wks'],
    name: 'kicad',
  },
  {
    fileExtensions: ['kitchen.yml', 'kitchen.yaml'],
    fileNames: [
      'kitchen.ci.yaml',
      'kitchen.dev.yaml',
      'kitchen.dev.yml',
      'kitchen.local.yaml',
      'kitchen.local.yml',
      'kitchen.prod.yaml',
      'kitchen.prod.yml',
      'kitchen.yaml',
      'kitchen.yml',
    ],
    name: 'kitchenci',
  },
  {
    fileExtensions: ['kite', 'kiteignore'],
    name: 'kite',
  },
  {
    fileExtensions: ['kv'],
    name: 'kivy',
  },
  {
    fileExtensions: ['kml'],
    name: 'kml',
  },
  {
    fileExtensions: ['kl'],
    name: 'kl',
  },
  {
    fileExtensions: ['knim', 'knime', 'knwf'],
    fileNames: ['knime.ini'],
    name: 'knime',
  },
  {
    fileNames: [
      'knip.js',
      'knip.cjs',
      'knip.mjs',
      'knip.ts',
      'knip.json',
      'knip.jsonc',
      'knip.config.js',
      'knip.config.cjs',
      'knip.config.mjs',
      'knip.config.ts',
      'knip.config.json',
      'knip.config.jsonc',
    ],
    name: 'knip',
  },
  {
    fileExtensions: ['knockout'],
    fileNames: ['knockout.js', 'knockout.min.js'],
    name: 'knockout',
  },
  {
    fileExtensions: ['kk', 'koka'],
    light: true,
    name: 'koka',
  },
  {
    fileExtensions: ['k8s', 'k8s.yaml', 'k8s.yml', 'kubernetes', 'kubernetes.yaml', 'kubernetes.yml'],
    fileNames: [
      'kubernetes',
      'kubernetes.dev.yaml',
      'kubernetes.dev.yml',
      'kubernetes.prod.yaml',
      'kubernetes.prod.yml',
      'kubernetes.yaml',
      'kubernetes.yml',
      'k8s.yaml',
      'k8s.yml',
    ],
    name: 'kubernetes',
  },
  {
    fileNames: [
      'configmap.yaml',
      'configmap.yml',
      'cronjob.yaml',
      'cronjob.yml',
      'daemonset.yaml',
      'daemonset.yml',
      'deployment.yaml',
      'deployment.yml',
      'ingress.yaml',
      'ingress.yml',
      'job.yaml',
      'job.yml',
      'persistentvolume.yaml',
      'persistentvolume.yml',
      'persistentvolumeclaim.yaml',
      'persistentvolumeclaim.yml',
      'pod.yaml',
      'pod.yml',
      'replicaset.yaml',
      'replicaset.yml',
      'replicationcontroller.yaml',
      'replicationcontroller.yml',
      'service.yaml',
      'service.yml',
      'statefulset.yaml',
      'statefulset.yml',
    ],
    name: 'kubernetesdepl',
  },
  {
    fileExtensions: ['kazel', 'kazelcfg.json'],
    fileNames: ['kazelcfg.json'],
    name: 'kazel',
  },
  {
    fileExtensions: ['csl', 'kql', 'kqlx', 'kusto'],
    name: 'kusto',
  },
  {
    fileNames: ['kustomization.yaml', 'kustomization.yml', 'kustomize.yaml', 'kustomize.yml'],
    name: 'kustomize',
  },
];
