export const mFiles = [
  {
    fileExtensions: ['m2'],
    name: 'macaulay',
  },
  {
    fileExtensions: ['mage'],
    name: 'magento',
  },
  {
    fileExtensions: ['magit'],
    name: 'magit',
  },
  {
    fileExtensions: ['am', 'mak', 'make', 'mk', 'mms'],
    name: 'make',
  },
  {
    fileNames: [
      'BSDmakefile',
      'GNUmakefile',
      'Kbuild',
      'Makefile.boot',
      'Makefile.in',
      'Makefile.inc',
      'Makefile.unix',
      'Makefile.unx',
      'Makefile.vc',
      'Makefile.wat',
      'Makefile.watcom',
      'Makefile.win',
      'makefile',
      'mkfile',
    ],
    name: 'makefile',
  },
  {
    fileExtensions: ['mako', 'mao'],
    name: 'mako',
  },
  {
    fileExtensions: [
      'man',
      'man1',
      'man2',
      'man3',
      'man4',
      'man5',
      'man6',
      'man7',
      'man8',
      'man9',
      'mdoc',
      'rnh',
      'rno',
      'roff',
      'runoff',
    ],
    name: 'manpage',
  },
  {
    fileNames: [
      'manifest',
      'manifest.bak',
      'manifest.json',
      'manifest.skip',
      'manifest.txt',
      'manifest.webapp',
      'manifest.xml',
      'manifest.yaml',
      'manifest.yml',
    ],
    name: 'manifest',
  },
  {
    fileExtensions: ['manifest', 'mf', 'webmanifest'],
    name: 'manifestfiles',
  },
  {
    fileExtensions: ['pkg.tar.bz2', 'pkg.tar.gz', 'pkg.tar.xz', 'pkg.tar.zst'],
    name: 'manjaro',
  },
  {
    fileExtensions: ['mss'],
    name: 'mapbox',
  },
  {
    fileExtensions: [
      'markdownlint',
      'markdownlint.json',
      'markdownlint.jsonc',
      'markdownlint.yaml',
      'markdownlint.yml',
      'markdownlintrc',
      'mdlrc',
    ],
    name: 'markdownlint',
  },
  {
    fileExtensions: ['markdownlintignore', 'mdlignore'],
    name: 'markdownlintignore',
  },
  {
    fileExtensions: ['marko', 'marko.js', 'marko.cjs', 'marko.mjs'],
    name: 'marko',
  },
  {
    fileExtensions: ['dhtm', 'dhtml', 'dtd', 'shtm', 'shtml', 'xht'],
    name: 'markup',
  },
  {
    fileNames: ['master.cjs', 'master.js', 'master.json', 'master.mjs', 'master.ts'],
    name: 'master',
  },
  {
    fileNames: [
      'materialize.cjs',
      'materialize.css',
      'materialize.js',
      'materialize.min.css',
      'materialize.min.js',
      'materialize.mjs',
      'materialize.scss',
    ],
    name: 'materialize',
  },
  {
    fileExtensions: ['ma', 'mb', 'mt', 'nb', 'nbp', 'math'],
    name: 'mathematica',
  },
  {
    fileExtensions: [
      'matlab',
      'mdlp',
      'mexglx',
      'mexmaci',
      'mexmaci64',
      'mexw',
      'mexw32',
      'mexw64',
      'mlappinstall',
      'mlpkginstall',
      'mltbx',
      'mlx',
      'mn',
      'sldd',
      'slx',
      'slxc',
      'slxp',
    ],
    name: 'matlab',
  },
  {
    fileExtensions: [
      'fig',
      'mex',
      'mexa',
      'mexn',
      'mexrs6',
      'mum',
      'mx',
      'mx3',
      'rwd',
      'smv',
      'xvc',
    ],
    name: 'matlabext',
  },
  {
    fileNames: [
      'MathJax-config.cjs',
      'MathJax-config.js',
      'MathJax-config.js.gz',
      'MathJax-config.js.map',
      'MathJax-config.mjs',
      'MathJax.cjs',
      'MathJax.js',
      'MathJax.js.gz',
      'MathJax.js.map',
      'MathJax.mjs',
      'TeX-MML-AM_CHTML.cjs',
      'TeX-MML-AM_CHTML.js',
      'TeX-MML-AM_CHTML.js.gz',
      'TeX-MML-AM_CHTML.js.map',
      'TeX-MML-AM_CHTML.mjs',
    ],
    name: 'mathjax',
  },
  {
    fileExtensions: ['pom', 'flattened-pom.xml'],
    fileNames: ['pom.xml'],
    name: 'maven',
  },
  {
    fileExtensions: ['maxhelp', 'maxobj', 'maxpat', 'maxproj', 'maxref', 'maxscript', 'mxt', 'pat'],
    name: 'max',
  },
  {
    fileExtensions: ['maya', 'mcfi', 'mcfp', 'mel'],
    name: 'maya',
  },
  {
    fileExtensions: ['mdx'],
    name: 'mdx',
  },
  {
    fileExtensions: ['mediawiki', 'wiki'],
    name: 'mediawiki',
  },
  {
    fileExtensions: ['hg', 'hgrc', 'hgsub', 'hgsubstate'],
    name: 'mercurial',
  },
  {
    fileExtensions: ['hgignore'],
    name: 'mercurialignore',
  },
  {
    fileExtensions: ['moo'],
    name: 'mercury',
  },
  {
    fileExtensions: ['merlin'],
    name: 'merlin',
  },
  {
    fileExtensions: ['mermaid', 'mmd', 'mmdc'],
    name: 'mermaid',
  },
  {
    fileNames: ['meson.build', 'meson_options.txt'],
    name: 'meson',
  },
  {
    fileExtensions: ['air', 'metal', 'metallib'],
    name: 'metal',
  },
  {
    fileExtensions: ['mp', 'mpost', 'mpx', 'mpy'],
    name: 'metapost',
  },
  {
    fileExtensions: ['meteor'],
    name: 'meteor',
  },
  {
    fileNames: ['mindsdb.js', 'mindsdb.ts', 'mindsdb.cjs', 'mindsdb.mjs', 'mindsdb.py'],
    name: 'mindsdb',
  },
  {
    fileExtensions: ['markuplintrc'],
    fileNames: [
      'markuplint.config.js',
      'markuplint.config.cjs',
      'markuplint.config.mjs',
      'markuplint.config.ts',
      'markuplint.config.json',
      'markuplint.config.yaml',
      'markuplint.config.yml',
    ],
    name: 'markuplint',
  },
  {
    fileExtensions: ['metadata', 'meta'],
    name: 'metadata',
  },
  {
    fileExtensions: ['mcfunction', 'mclevel', 'mcmeta', 'mcmod', 'mcpack', 'mcrcon', 'mcreator', 'mcworld'],
    name: 'minecraft',
  },
  {
    fileExtensions: ['dzn', 'fzn', 'mzn'],
    name: 'minizinc',
  },
  {
    fileExtensions: ['mint'],
    name: 'mint',
  },
  {
    fileNames: ['mint.json'],
    name: 'mintlify',
  },
  {
    fileNames: ['mist.cjs', 'mist.js', 'mist.jsx', 'mist.mjs', 'mist.ts', 'mist.tsx'],
    name: 'mist',
  },
  {
    fileExtensions: ['druby', 'duby', 'mir', 'mirah'],
    name: 'mirah',
  },
  {
    fileExtensions: ['mixin', 'mixin.json', 'mixins', 'mixins.json'],
    name: 'mixin',
  },
  {
    fileExtensions: ['mirc', 'mircscript', 'mrc'],
    name: 'mirc',
  },
  {
    fileExtensions: ['mjml', 'mjmlslim'],
    name: 'mjml',
  },
  {
    fileExtensions: ['mkdocs.yml', 'mkdocs.yaml'],
    fileNames: ['mkdocs.yml', 'mkdocs.yaml'],
    name: 'mkdocs',
  },
  {
    fileExtensions: ['mlang', 'pq'],
    name: 'mlang',
  },
  {
    fileExtensions: [
      'mobx',
      'mobx.cjs',
      'mobx.js',
      'mobx.mjs',
      'mobx.ts',
      'observable.cjs',
      'observable.js',
      'observable.mjs',
      'observable.ts',
    ],
    name: 'mobx',
  },
  {
    fileNames: ['mocha.opts'],
    name: 'mocha',
  },
  {
    fileExtensions: [
      'mocha.cjs',
      'mocha.js',
      'mocha.json',
      'mocha.mjs',
      'mocha.ts',
      'mocha.yaml',
      'mocha.yml',
      'mocharc',
      'mocharc.js',
      'mocharc.json',
    ],
    name: 'mochajson',
  },
  {
    fileExtensions: [
      'mock.cjs',
      'mock.cs',
      'mock.dart',
      'mock.go',
      'mock.java',
      'mock.js',
      'mock.json',
      'mock.mjs',
      'mock.php',
      'mock.pl',
      'mock.py',
      'mock.rb',
      'mock.swift',
      'mock.ts',

      'spy',
      'spy.cjs',
      'spy.cs',
      'spy.dart',
      'spy.go',
      'spy.java',
      'spy.js',
      'spy.json',
      'spy.mjs',
      'spy.php',
      'spy.pl',
      'spy.py',
      'spy.rb',
      'spy.swift',
      'spy.ts',

      'stub.cjs',
      'stub.cs',
      'stub.dart',
      'stub.go',
      'stub.java',
      'stub.js',
      'stub.json',
      'stub.mjs',
      'stub.php',
      'stub.pl',
      'stub.py',
      'stub.rb',
      'stub.swift',
      'stub.ts',
    ],
    name: 'mock',
  },
  {
    fileExtensions: [
      'mock/cjs',
      'mock/cs',
      'mock/dart',
      'mock/go',
      'mock/java',
      'mock/js',
      'mock/json',
      'mock/mjs',
      'mock/php',
      'mock/pl',
      'mock/py',
      'mock/rb',
      'mock/swift',
      'mock/ts',

      'mocks/cjs',
      'mocks/cs',
      'mocks/dart',
      'mocks/go',
      'mocks/java',
      'mocks/js',
      'mocks/json',
      'mocks/mjs',
      'mocks/php',
      'mocks/pl',
      'mocks/py',
      'mocks/rb',
      'mocks/swift',
      'mocks/ts',
    ],
    name: 'mockfiles',
  },
  {
    fileExtensions: ['mo', 'mos'],
    name: 'modelica',
  },
  {
    fileExtensions: [
      'modernizrrc',
      'modernizrrc.cjs',
      'modernizrrc.js',
      'modernizrrc.json',
      'modernizrrc.mjs',
      'modernizrrc.ts',
    ],
    fileNames: [
      'modernizr-dev.cjs',
      'modernizr-dev.js',
      'modernizr-dev.mjs',
      'modernizr-dev.ts',
      'modernizr.cjs',
      'modernizr.custom.cjs',
      'modernizr.custom.js',
      'modernizr.custom.mjs',
      'modernizr.custom.ts',
      'modernizr.js',
      'modernizr.json',
      'modernizr.mjs',
      'modernizr.ts',
    ],
    name: 'modernizr',
  },
  {
    fileNames: [
      'web-dev-server.config.cjs',
      'web-dev-server.config.js',
      'web-dev-server.config.mjs',
      'web-dev-server.config.ts',
      'web-test-runner.config.cjs',
      'web-test-runner.config.js',
      'web-test-runner.config.mjs',
      'web-test-runner.config.ts',
    ],
    name: 'modernweb',
  },
  {
    fileExtensions: ['lxo', 'modo'],
    name: 'modo',
  },
  {
    fileExtensions: ['def', 'mod'],
    name: 'modula2',
  },
  {
    fileExtensions: ['i3', 'ig', 'm3', 'mg'],
    fileNames: ['m3config', 'm3makefile', 'm3overrides'],
    name: 'modula3',
  },
  {
    fileExtensions: ['moho', 'mohoaction', 'mohobrush', 'mohoexport', 'mohoproj', 'mohostyle'],
    name: 'moho',
  },
  {
    fileExtensions: ['ep', 'epl'],
    name: 'mojolicious',
  },
  {
    fileNames: [
      'moleculer.config.cjs',
      'moleculer.config.js',
      'moleculer.config.json',
      'moleculer.config.mjs',
      'moleculer.config.ts',
    ],
    name: 'moleculer',
  },
  {
    fileNames: [
      'moment-with-locales.cjs',
      'moment-with-locales.js',
      'moment-with-locales.mjs',
      'moment.cjs',
      'moment.js',
      'moment.min.cjs',
      'moment.min.js',
      'moment.min.mjs',
      'moment.mjs',
    ],
    name: 'moment',
  },
  {
    fileExtensions: ['monkey'],
    name: 'monkey',
  },
  {
    fileExtensions: ['bson', 'mongo', 'mongodb'],
    name: 'mongodb',
  },
  {
    fileExtensions: ['monotone', 'mtn', 'mtn-ignore'],
    name: 'monotone',
  },
  {
    fileExtensions: ['moon'],
    name: 'moonscript',
  },
  {
    fileNames: [
      'mootools-core.cjs',
      'mootools-core.js',
      'mootools-core.mjs',
      'mootools-nocompat.cjs',
      'mootools-nocompat.js',
      'mootools-nocompat.min.js',
      'mootools-nocompat.mjs',
      'mootools.cjs',
      'mootools.js',
      'mootools.min.js',
      'mootools.mjs',
    ],
    name: 'mootools',
  },
  {
    fileExtensions: ['more', 'msg', 'utf8'],
    name: 'more',
  },
  {
    fileExtensions: ['mrb'],
    name: 'mruby',
  },
  {
    fileExtensions: ['chk', 'com', 'dos', 'ful'],
    name: 'msdos',
  },
  {
    fileExtensions: ['mson'],
    name: 'mson',
  },
  {
    fileExtensions: ['ldf', 'mdf', 'ndf'],
    name: 'msql',
  },
  {
    fileExtensions: ['mnb', 'mu', 'mup', 'mupad', 'mupadnotebook'],
    name: 'mupad',
  },
  {
    fileExtensions: ['emblem', 'hamlbars', 'handlebars', 'hbs', 'mustache', 'stache'],
    name: 'mustache',
  },
  {
    fileExtensions: ['mxml'],
    name: 'mxml',
  },
  {
    fileNames: ['mybatis-config.xml', 'mybatis.xml'],
    name: 'mybatis',
  },
];
