import { IconPack } from 'src/@types/config';

export const rFiles = [
  {
    fileExtensions: ['r', 'rd', 'rhistory', 'rprofile', 'rsx'],
    name: 'r',
  },
  {
    fileExtensions: ['rmd', 'rmarkdown'],
    name: 'rmd',
  },
  {
    fileExtensions: ['rkt', 'rktd', 'rktl', 'scrbl'],
    name: 'racket',
  },
  {
    fileExtensions: ['raml'],
    name: 'raml',
  },
  {
    fileExtensions: ['rails'],
    fileNames: ['rails'],
    name: 'rails',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['channel/rb', 'channels/rb'],
    name: 'railschannelfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['concern/rb', 'concerns/rb'],
    name: 'railsconcernfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['controller/rb', 'controllers/rb'],
    name: 'railscontrollerfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileNames: ['database.yml', 'database.yaml'],
    name: 'railsdbfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['factory/rb', 'factories/rb'],
    name: 'railsfactoryfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['fixture/rb', 'fixtures/rb'],
    name: 'railsfixturefiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['helper/rb', 'helpers/rb'],
    name: 'railshelperfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['job/rb', 'jobs/rb'],
    name: 'railsjobfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['mailer/rb', 'mailers/rb'],
    name: 'railsmailerfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileNames: ['routes.rb'],
    name: 'railsroutesfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['schema/rb', 'schemas/rb'],
    name: 'railsschemafiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['serializer/rb', 'serializers/rb'],
    name: 'railsserializerfiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileExtensions: ['service/rb', 'services/rb'],
    name: 'railsservicefiles',
  },
  {
    enabledFor: [IconPack.Rails],
    fileNames: ['seed.rb'],
    name: 'railsseedfiles',
  },
  {
    fileExtensions: ['rake'],
    name: 'rake',
  },
  {
    fileNames: ['rakefile', 'rakefile.rb'],
    name: 'rakefile',
  },
  {
    fileExtensions: ['cshtml', 'vbhtml'],
    name: 'razor',
  },
  {
    fileNames: [
      'raphael-min.js',
      'raphael.js',
      'raphael.min.js',
      'raphael.no-deps.cjs',
      'raphael.no-deps.js',
      'raphael.no-deps.mjs',
    ],
    name: 'raphael',
  },
  {
    fileExtensions: ['rsc', 'rascal'],
    name: 'rascal',
  },
  {
    fileNames: [
      'razzle.config.cjs',
      'razzle.config.js',
      'razzle.config.mjs',
      'razzle.config.ts',
      'razzle.config.yaml',
      'razzle.config.yml',
    ],
    name: 'razzle',
  },
  {
    fileExtensions: ['rbs'],
    name: 'rbs',
  },
  {
    fileExtensions: ['rda', 'rdata', 'rds', 'rdx'],
    name: 'rdata',
  },
  {
    fileExtensions: ['rdoc'],
    name: 'rdoc',
  },
  {
    fileExtensions: ['readthedocs', 'readthedocs.yaml', 'readthedocs.yml'],
    name: 'readthedocs',
  },
  {
    enabledFor: [IconPack.Recoil],
    fileExtensions: [
      'atom.js',
      'atom.ts',
      'atoms.js',
      'atoms.ts',
      'selector.js',
      'selector.ts',
      'selectors.js',
      'selectors.ts',
    ],
    fileNames: [
      'atom.js',
      'atom.ts',
      'atoms.js',
      'atoms.ts',
      'selector.js',
      'selector.ts',
      'selectors.js',
      'selectors.ts',
    ],
    name: 'recoil',
  },
  {
    enabledFor: [IconPack.Recoil],
    fileExtensions: [
      'atoms/js',
      'atoms/jsx',
      'atoms/ts',
      'atoms/tsx',
      'recoil/js',
      'recoil/jsx',
      'recoil/ts',
      'recoil/tsx',
    ],
    name: 'recoilfiles',
  },
  {
    fileNames: [
      'remix.config.cjs',
      'remix.config.js',
      'remix.config.mjs',
      'remix.config.ts',
      'remix.config.yaml',
      'remix.config.yml',
    ],
    name: 'remix',
  },
  {
    fileExtensions: ['replit'],
    name: 'replit',
  },
  {
    fileExtensions: ['restql', 'rql'],
    name: 'restql',
  },
  {
    fileNames: ['restql.conf.json', 'restql.conf.yaml', 'restql.yaml', 'restql.yml'],
    name: 'restqlconf',
  },
  {
    fileExtensions: ['reactcli', 'react-cli'],
    name: 'reactcli',
  },
  {
    fileNames: ['react-min.js', 'react.cjs', 'react.js', 'react.min.js', 'react.mjs', 'react.production.min.js'],
    name: 'react',
  },
  {
    fileNames: ['reactos.deb', 'reactos.ios'],
    name: 'reactos',
  },
  {
    fileExtensions: ['re', 'rei'],
    name: 'reason',
  },
  {
    fileExtensions: ['reason', 'rns', 'rsn', 'rx2', 'sxt'],
    name: 'reasonstudios',
  },
  {
    fileExtensions: ['r2', 'r3', 'reb', 'rebol'],
    name: 'rebol',
  },
  {
    fileExtensions: ['rpm', 'rpmmacros', 'srpm'],
    name: 'redhat',
  },
  {
    fileExtensions: ['red', 'reds'],
    name: 'red',
  },
  {
    fileExtensions: ['rdb'],
    fileNames: ['redis.conf', 'redis-config.yml', 'redis-config.yaml'],
    name: 'redis',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'action.js',
      'action.jsx',
      'action.ts',
      'action.tsx',
      'actions.js',
      'actions.jsx',
      'actions.ts',
      'actions.tsx',
    ],
    fileNames: [
      'action.js',
      'action.jsx',
      'action.ts',
      'action.tsx',
      'actions.js',
      'actions.jsx',
      'actions.ts',
      'actions.tsx',
    ],
    name: 'redux-action',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'action/js',
      'action/jsx',
      'action/ts',
      'action/tsx',
      'actions/js',
      'actions/jsx',
      'actions/ts',
      'actions/tsx',
    ],
    name: 'redux-action-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'epic.js',
      'epic.jsx',
      'epic.ts',
      'epic.tsx',
      'epics.js',
      'epics.jsx',
      'epics.ts',
      'epics.tsx',
    ],
    fileNames: ['epic.js', 'epic.jsx', 'epic.ts', 'epic.tsx', 'epics.js', 'epics.jsx', 'epics.ts', 'epics.tsx'],
    name: 'redux-epic',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'epic/js',
      'epic/jsx',
      'epic/ts',
      'epic/tsx',
      'epics/js',
      'epics/jsx',
      'epics/ts',
      'epics/tsx',
    ],
    name: 'redux-epic-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'thunk.js',
      'thunk.jsx',
      'thunk.ts',
      'thunk.tsx',
      'thunks.js',
      'thunks.jsx',
      'thunks.ts',
      'thunks.tsx',
    ],
    fileNames: [
      'thunk.js',
      'thunk.jsx',
      'thunk.ts',
      'thunk.tsx',
      'thunks.js',
      'thunks.jsx',
      'thunks.ts',
      'thunks.tsx',
    ],
    name: 'redux-thunk',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'thunks/js',
      'thunks/jsx',
      'thunks/ts',
      'thunks/tsx',
    ],
    name: 'redux-thunk-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'saga.js',
      'saga.jsx',
      'saga.ts',
      'saga.tsx',
      'sagas.js',
      'sagas.jsx',
      'sagas.ts',
      'sagas.tsx',
    ],
    fileNames: ['saga.js', 'saga.jsx', 'saga.ts', 'saga.tsx', 'sagas.js', 'sagas.jsx', 'sagas.ts', 'sagas.tsx'],
    name: 'redux-saga',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'saga/js',
      'saga/jsx',
      'saga/ts',
      'saga/tsx',
      'sagas/js',
      'sagas/jsx',
      'sagas/ts',
      'sagas/tsx',
    ],
    name: 'redux-saga-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'selector.js',
      'selector.jsx',
      'selector.ts',
      'selector.tsx',
      'selectors.js',
      'selectors.jsx',
      'selectors.ts',
      'selectors.tsx',
    ],
    fileNames: [
      'selector.js',
      'selector.jsx',
      'selector.ts',
      'selector.tsx',
      'selectors.js',
      'selectors.jsx',
      'selectors.ts',
      'selectors.tsx',
    ],
    name: 'redux-selector',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'selector/js',
      'selector/jsx',
      'selector/ts',
      'selector/tsx',
      'selectors/js',
      'selectors/jsx',
      'selectors/ts',
      'selectors/tsx',
    ],
    name: 'redux-selector-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'reducer.js',
      'reducer.jsx',
      'reducer.ts',
      'reducer.tsx',
      'reducers.js',
      'reducers.jsx',
      'reducers.ts',
      'reducers.tsx',
    ],
    fileNames: [
      'reducer.js',
      'reducer.jsx',
      'reducer.ts',
      'reducer.tsx',
      'reducers.js',
      'reducers.jsx',
      'reducers.ts',
      'reducers.tsx',
    ],
    name: 'redux-reducer',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'reducer/js',
      'reducer/jsx',
      'reducer/ts',
      'reducer/tsx',
      'reducers/js',
      'reducers/jsx',
      'reducers/ts',
      'reducers/tsx',
    ],
    name: 'redux-reducer-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'slice.js',
      'slice.jsx',
      'slice.ts',
      'slice.tsx',
      'slices.js',
      'slices.jsx',
      'slices.ts',
      'slices.tsx',
    ],
    fileNames: [
      'slice.js',
      'slice.jsx',
      'slice.ts',
      'slice.tsx',
      'slices.js',
      'slices.jsx',
      'slices.ts',
      'slices.tsx',
    ],
    name: 'redux-slice',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'slice/js',
      'slice/jsx',
      'slice/ts',
      'slice/tsx',
      'slices/js',
      'slices/jsx',
      'slices/ts',
      'slices/tsx',
    ],
    name: 'redux-slice-files',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'store.js',
      'store.jsx',
      'store.ts',
      'store.tsx',
      'store/js',
      'store/jsx',
      'store/ts',
      'store/tsx',
      'stores.js',
      'stores.jsx',
      'stores.ts',
      'stores.tsx',
      'stores/js',
      'stores/jsx',
      'stores/ts',
      'stores/tsx',
    ],
    fileNames: [
      'store.js',
      'store.jsx',
      'store.ts',
      'store.tsx',
      'stores.js',
      'stores.jsx',
      'stores.ts',
      'stores.tsx',
    ],
    name: 'redux-store',
  },
  {
    enabledFor: [IconPack.Redux],
    fileExtensions: [
      'store/js',
      'store/jsx',
      'store/ts',
      'store/tsx',
      'stores/js',
      'stores/jsx',
      'stores/ts',
      'stores/tsx',
    ],
    name: 'redux-store-files',
  },
  {
    fileExtensions: ['reek'],
    name: 'reek',
  },
  {
    fileExtensions: ['regex', 'regexp', 'rgx'],
    name: 'regex',
  },
  {
    fileExtensions: [
      'reh',
      'rehype',
      'rehyperc',
      'rehyperc.cjs',
      'rehyperc.js',
      'rehyperc.json',
      'rehyperc.mjs',
      'rehyperc.ts',
      'rehyperc.yaml',
      'rehyperc.yml',
    ],
    name: 'rehype',
  },
  {
    fileExtensions: ['rehypeignore'],
    name: 'rehypeignore',
  },
  {
    fileExtensions: [
      'remark',
      'remarkrc',
      'remarkrc.cjs',
      'remarkrc.js',
      'remarkrc.json',
      'remarkrc.mjs',
      'remarkrc.ts',
      'remarkrc.yaml',
      'remarkrc.yml',
    ],
    name: 'remark',
  },
  {
    fileExtensions: [
      'retext',
      'retextrc',
      'retextrc.cjs',
      'retextrc.js',
      'retextrc.json',
      'retextrc.mjs',
      'retextrc.ts',
      'retextrc.yaml',
      'retextrc.yml',
    ],
    name: 'retext',
  },
  {
    fileExtensions: ['retextignore'],
    name: 'retextignore',
  },
  {
    fileExtensions: ['remarkignore'],
    name: 'remarkignore',
  },
  {
    fileExtensions: ['renovaterc'],
    fileNames: ['renovate.json', 'renovate.json5', 'renovate.jsonc'],
    name: 'renovate',
  },
  {
    fileNames: ['require-dev.js', 'require.cjs', 'require.js', 'require.min.js', 'require.mjs'],
    name: 'requirejs',
  },
  {
    fileExtensions: ['res', 'resi'],
    name: 'rescript',
  },
  {
    fileExtensions: ['rst'],
    name: 'rst',
  },
  {
    fileExtensions: ['pprx', 'rex', 'rexx'],
    name: 'rexx',
  },
  {
    fileNames: [
      'rspack.config.js',
      'rspack.config.cjs',
      'rspack.config.mjs',
      'rspack.config.ts',
      'rsbuild.config.js',
      'rsbuild.config.cjs',
      'rsbuild.config.mjs',
      'rsbuild.config.ts',
      'rspress.config.js',
      'rspress.config.cjs',
      'rspress.config.mjs',
      'rspress.config.ts',
    ],
    name: 'rspack',
  },
  {
    fileExtensions: ['3dmf', '3dmr', '3mf', '3mfz', '3mm', 'rvb'],
    name: 'rhino3d',
  },
  {
    fileNames: ['riemann.config'],
    name: 'riemann',
  },
  {
    fileNames: ['rindo.config.js', 'rindo.config.cjs', 'rindo.config.mjs', 'rindo.config.ts'],
    name: 'rindo',
  },
  {
    fileExtensions: ['ring'],
    name: 'ring',
  },
  {
    fileExtensions: ['riot'],
    name: 'riot',
  },
  {
    fileExtensions: ['robot'],
    name: 'robot',
  },
  {
    fileNames: ['robots.txt', 'robots'],
    name: 'robots',
  },
  {
    fileNames: [
      'rollup.cjs',
      'rollup.conf.cjs',
      'rollup.conf.js',
      'rollup.conf.mjs',
      'rollup.conf.ts',
      'rollup.config.cjs',
      'rollup.config.js',
      'rollup.config.mjs',
      'rollup.config.ts',
      'rollup.js',
      'rollup.mjs',
      'rollup.ts',
    ],
    name: 'rollup',
  },
  {
    fileExtensions: ['rome', 'romeignore'],
    fileNames: ['rome.json'],
    name: 'rome',
  },
  {
    fileNames: [
      'routes.js',
      'routes.jsx',
      'routes.ts',
      'routes.tsx',
      'routing.js',
      'routing.jsx',
      'routing.ts',
      'routing.tsx',
    ],
    name: 'routes',
  },
  {
    fileExtensions: [
      'router/js',
      'router/jsx',
      'router/ts',
      'router/tsx',
      'routes/js',
      'routes/jsx',
      'routes/ts',
      'routes/tsx',
      'routing/js',
      'routing/jsx',
      'routing/ts',
      'routing/tsx',
    ],
    name: 'routesfiles',
  },
  {
    fileExtensions: ['rproj'],
    name: 'rstudio',
  },
  {
    fileExtensions: ['rspec'],
    name: 'rspec',
  },
  {
    fileExtensions: ['rspec/rb', 'rspec/rbs'],
    name: 'rspecfiles',
  },
  {
    fileExtensions: ['rss'],
    name: 'rss',
  },
  {
    fileNames: ['rsyncd.conf', 'rsyncd.secrets'],
    light: true,
    name: 'rsync',
  },
  {
    fileExtensions: ['rubocop.yaml', 'rubocop.yml', 'rubocop_todo.yml'],
    name: 'rubocop',
  },
  {
    fileExtensions: ['gem', 'gemspec'],
    name: 'rubygems',
  },
  {
    fileExtensions: ['gemrc', 'irbrc', 'pryrc', 'rubyrc'],
    name: 'rubyrc',
  },
  {
    fileExtensions: ['rb-gemset', 'ruby-gemset'],
    name: 'gemset',
  },
  {
    fileExtensions: ['rb-version', 'ruby-version'],
    name: 'rubyversion',
  },
  {
    fileExtensions: ['rlib', 'rlibc', 'rlibm', 'rlibstd', 'rs', 'rs.in', 'rust'],
    name: 'rust',
  },
  {
    fileExtensions: ['ron'],
    name: 'ron',
  },
  {
    fileExtensions: ['rust-toolchain'],
    name: 'rusttoolchain',
  },
  {
    fileExtensions: ['rvmrc'],
    name: 'rvm',
  },
  {
    fileNames: ['rxjs.js', 'rxjs.json', 'rxjs.ts'],
    name: 'rxjs',
  },
];
