export const sFiles = [
  {
    fileExtensions: ['sac'],
    name: 'sac',
  },
  {
    fileExtensions: ['binarycookies', 'safariext', 'safariextz', 'webarchive'],
    name: 'safari',
  },
  {
    fileExtensions: ['sage', 'sagews'],
    name: 'sage',
  },
  {
    fileExtensions: ['sailsrc'],
    name: 'sails',
  },
  {
    fileExtensions: ['sls'],
    name: 'saltstack',
  },
  {
    fileExtensions: ['san'],
    name: 'san',
  },
  {
    fileExtensions: ['sb'],
    name: 'sandbox',
  },
  {
    fileExtensions: ['sas'],
    name: 'sas',
  },
  {
    fileNames: [
      'sapper.cjs',
      'sapper.config.cjs',
      'sapper.config.js',
      'sapper.config.mjs',
      'sapper.config.ts',
      'sapper.js',
      'sapper.mjs',
      'sapper.ts',
    ],
    name: 'sapper',
  },
  {
    fileExtensions: ['sbt'],
    name: 'sbt',
  },
  {
    fileExtensions: ['kojo', 'sc'],
    name: 'scala',
  },
  {
    fileExtensions: ['scons', 'scsub', 'sconscript', 'sconstruct', 'dblite'],
    name: 'scons',
  },
  {
    fileExtensions: ['scheme', 'scm', 'sld', 'sps', 'xtm'],
    name: 'scheme',
  },
  {
    fileExtensions: ['scilla'],
    name: 'scilla',
  },
  {
    fileExtensions: ['sci', 'sce', 'tst'],
    name: 'scilab',
  },
  {
    fileExtensions: ['sb2', 'sb3'],
    name: 'scratch',
  },
  {
    fileExtensions: ['scrutinizer.yml', 'scrutinizer.yaml'],
    name: 'scrutinizer',
  },
  {
    fileExtensions: ['sdl'],
    name: 'sdlang',
  },
  {
    fileExtensions: ['safe', 'secret', 'secrets'],
    name: 'secret',
  },
  {
    fileExtensions: ['self'],
    name: 'self',
  },
  {
    fileNames: [
      'sencha-touch.js',
      'sencha-touch.min.js',
      'sencha.cjs',
      'sencha.js',
      'sencha.min.cjs',
      'sencha.min.js',
      'sencha.min.mjs',
      'sencha.mjs',
    ],
    name: 'sencha',
  },
  {
    fileExtensions: ['sentryclirc'],
    fileNames: [
      'sentry.client.config.js',
      'sentry.client.config.mjs',
      'sentry.client.config.cjs',
      'sentry.client.config.ts',
      'sentry.server.config.js',
      'sentry.server.config.mjs',
      'sentry.server.config.cjs',
      'sentry.server.config.ts',
    ],
    name: 'sentry',
  },
  {
    fileExtensions: [
      'releaserc',
      'releaserc.cjs',
      'releaserc.js',
      'releaserc.json',
      'releaserc.mjs',
      'releaserc.yaml',
      'releaserc.yml',
    ],
    name: 'semantic-release',
  },
  {
    fileNames: [
      'release.config.cjs',
      'release.config.js',
      'release.config.mjs',
      'semantic-release.config.cjs',
      'semantic-release.config.js',
      'semantic-release.config.mjs',
    ],
    name: 'semantic-release-config',
  },
  {
    fileExtensions: ['semgrep', 'semgrepignore'],
    name: 'semgrep',
  },
  {
    fileExtensions: [
      'serverless.cjs',
      'serverless.js',
      'serverless.json',
      'serverless.mjs',
      'serverless.ts',
      'serverless.yaml',
      'serverless.yml',
    ],
    fileNames: [
      'serverless.cjs',
      'serverless.js',
      'serverless.json',
      'serverless.mjs',
      'serverless.ts',
      'serverless.yaml',
      'serverless.yml',
    ],
    name: 'serverless',
  },
  {
    fileExtensions: ['sfproj'],
    name: 'servicefabric',
  },
  {
    fileExtensions: ['opt', 'option', 'options', 'opts', 'setting', 'settings'],
    name: 'settings',
  },
  {
    fileExtensions: ['sequelizerc', 'sequelizerc.cjs', 'sequelizerc.js', 'sequelizerc.json', 'sequelizerc.mjs'],
    name: 'sequelize',
  },
  {
    fileNames: ['shadow-cljs.edn'],
    name: 'shadowcljs',
  },
  {
    fileExtensions: ['shen'],
    name: 'shen',
  },
  {
    fileExtensions: ['shellcheckrc'],
    fileNames: ['shellcheckrc'],
    name: 'shellcheck',
  },
  {
    fileExtensions: [
      'bash',
      'bash_aliases',
      'bash_functions',
      'bash_profile',
      'bashrc',
      'elvish',
      'fish',
      'fishrc',
      'nush',
      'nushell',
      'nurc',
      'tcsh',
      'tcshrc',
      'zprofile',
      'zsh',
      'zshenv',
      'zshrc',
    ],
    name: 'shell',
  },
  {
    fileExtensions: [
      'ash',
      'csh',
      'cshrc',
      'dash',
      'ion',
      'ksh',
      'kshrc',
      'mksh',
      'mkshrc',
      'oksh',
      'osh',
      'pdkshrc',
      'pksh',
      'pkshrc',
      'scsh',
      'shar',
      'xiki',
      'xonsh',
      'yash',
    ],
    name: 'shell2',
  },
  {
    fileNames: ['shipitfile.babel.js', 'shipitfile.cjs', 'shipitfile.js', 'shipitfile.mjs', 'shipitfile.ts'],
    name: 'shipit',
  },
  {
    fileNames: ['shippable.yml', 'shippable.yaml'],
    name: 'shippable',
  },
  {
    fileExtensions: ['sigils'],
    name: 'sigils',
  },
  {
    fileExtensions: ['ss'],
    name: 'silverstripe',
  },
  {
    fileExtensions: ['siyuan', 'sy'],
    name: 'siyuan',
  },
  {
    fileExtensions: ['sketch'],
    name: 'sketch',
  },
  {
    fileExtensions: ['layout', 'skd', 'sketchup', 'sketchupproj', 'skm'],
    name: 'sketchup',
  },
  {
    fileExtensions: ['skp', 'style'],
    name: 'sketchmake',
  },
  {
    fileExtensions: ['eskip'],
    name: 'skipper',
  },
  {
    fileExtensions: ['sk', 'skript'],
    light: true,
    name: 'skript',
  },
  {
    fileExtensions: ['slang'],
    name: 'slang',
  },
  {
    fileExtensions: ['slash', 'sl'],
    name: 'slash',
  },
  {
    fileExtensions: ['ice'],
    name: 'slice',
  },
  {
    fileExtensions: ['slim'],
    name: 'slim',
  },
  {
    fileNames: [
      '[slug].cjs',
      '[slug].js',
      '[slug].jsx',
      '[slug].mjs',
      '[slug].php',
      '[slug].ts',
      '[slug].tsx',
    ],
    name: 'slug',
  },
  {
    fileNames: [
      'slugs/cjs',
      'slugs/js',
      'slugs/jsx',
      'slugs/mjs',
      'slugs/php',
      'slugs/ts',
      'slugs/tsx',
    ],
    name: 'slugfiles',
  },
  {
    fileNames: ['smartos.deb', 'smartos.img', 'smartos.iso'],
    name: 'smartos',
  },
  {
    fileExtensions: ['smarty', 'tpl'],
    name: 'smarty',
  },
  {
    fileExtensions: ['smithy'],
    name: 'smithy',
  },
  {
    fileExtensions: ['cm', 'fun', 'grm', 'mlb', 'mlton', 'sig', 'sml'],
    name: 'sml',
  },
  {
    fileExtensions: ['bam', 'rule', 'smk'],
    name: 'snakemake',
  },
  {
    fileNames: ['snakefile'],
    name: 'snakefile',
  },
  {
    fileNames: ['snapcraft.yaml', 'snapcraft.yml'],
    name: 'snapcraft',
  },
  {
    fileNames: ['snap.svg-min.js', 'snap.svg.cjs', 'snap.svg.js', 'snap.svg.min.js', 'snap.svg.mjs'],
    name: 'snapsvg',
  },
  {
    fileExtensions: ['snap'],
    name: 'snapshot',
  },
  {
    fileExtensions: ['snort'],
    name: 'snort',
  },
  {
    fileNames: [
      'snowpack.config.cjs',
      'snowpack.config.js',
      'snowpack.config.json',
      'snowpack.config.mjs',
      'snowpack.config.ts',
      'snowpack.config.yaml',
      'snowpack.config.yml',
    ],
    name: 'snowpack',
  },
  {
    fileExtensions: ['snyk'],
    name: 'snyk',
  },
  {
    fileExtensions: ['sol', 'solidity'],
    name: 'solidity',
  },
  {
    fileExtensions: ['solidarity', 'solidarity.json'],
    name: 'solidarity',
  },
  {
    fileExtensions: ['sonar', 'sonarlint', 'sonarlintignore', 'sonarqube', 'sonarrc'],
    name: 'sonar',
  },
  {
    fileExtensions: ['sonarcloud.properties', 'sonarcloud.yaml', 'sonarcloud.yml'],
    fileNames: [
      'sonar-project.json',
      'sonar-project.properties',
      'sonar-project.yaml',
      'sonar-project.yml',
      'sonarcloud.json',
      'sonarcloud.properties',
      'sonarcloud.yaml',
      'sonarcloud.yml',
    ],
    name: 'sonarcloud',
  },
  {
    fileExtensions: ['aesl', 'aes'],
    name: 'sophia',
  },
  {
    fileExtensions: ['rbi'],
    name: 'sorbet',
  },
  {
    fileExtensions: ['cidmap', 'enigma', 'map', 'mapping', 'match', 'tiny', 'tinyv2'],
    name: 'sourcemap',
  },
  {
    fileExtensions: ['spe'],
    name: 'spaceengine',
  },
  {
    fileExtensions: ['spacemacs'],
    fileNames: ['spacemacs'],
    name: 'spacemacs',
  },
  {
    fileExtensions: ['rq', 'sparql'],
    name: 'sparql',
  },
  {
    fileExtensions: ['spectral.yml', 'spectral.yaml'],
    name: 'spectral',
  },
  {
    fileExtensions: ['spring'],
    name: 'spring',
  },
  {
    fileExtensions: ['spwn'],
    name: 'spwn',
  },
  {
    fileExtensions: ['hqf', 'sqf'],
    name: 'sqf',
  },
  {
    fileExtensions: ['cql', 'hql', 'mysql', 'pdb', 'prc', 'viw', 'xq', 'xql', 'xqm', 'xqy'],
    name: 'sql',
  },
  {
    fileExtensions: ['sqlite', 'sqlite3', 'sqlite3-journal'],
    name: 'sqlite',
  },
  {
    fileExtensions: ['jsont'],
    name: 'squarespace',
  },
  {
    fileExtensions: ['gnut', 'nut', 'nutf'],
    name: 'squirrel',
  },
  {
    fileExtensions: ['sst'],
    fileNames: ['sst.config.js', 'sst.config.ts', 'sst.config.cjs', 'sst.config.mjs'],
    name: 'sst',
  },
  {
    fileExtensions: ['stan'],
    name: 'stan',
  },
  {
    fileExtensions: ['ado', 'doh', 'ihlp', 'mata', 'matah', 'oh', 'stata', 'sthlp'],
    name: 'stata',
  },
  {
    fileNames: [
      'stdlib.cjs',
      'stdlib.conf.cjs',
      'stdlib.conf.js',
      'stdlib.conf.mjs',
      'stdlib.conf.ts',
      'stdlib.js',
      'stdlib.min.cjs',
      'stdlib.min.js',
      'stdlib.min.mjs',
      'stdlib.mjs',
      'stdlib.ts',
    ],
    name: 'stdlib',
  },
  {
    fileNames: ['stencil.config.js', 'stencil.config.ts'],
    name: 'stencilconfig',
  },
  {
    fileExtensions: ['stencil'],
    name: 'stencil',
  },
  {
    fileExtensions: ['steadybit.yml', 'steadybit.yaml'],
    fileNames: ['steadybit.yml', 'steadybit.yaml'],
    name: 'steadybit',
  },
  {
    fileExtensions: ['stitches.config.cjs', 'stitches.config.js', 'stitches.config.mjs', 'stitches.config.ts'],
    fileNames: ['stitches.config.cjs', 'stitches.config.js', 'stitches.config.mjs', 'stitches.config.ts'],
    name: 'stitches',
  },
  {
    fileExtensions: ['storyboard'],
    name: 'storyboard',
  },
  {
    fileExtensions: ['story'],
    name: 'storyist',
  },
  {
    fileExtensions: [
      'stories.js',
      'stories.jsx',
      'stories.mdx',
      'stories.ts',
      'stories.tsx',
      'story.js',
      'story.jsx',
      'story.mdx',
      'story.ts',
      'story.tsx',
    ],
    name: 'storybook',
  },
  {
    fileExtensions: [
      '.storybook/js',
      '.storybook/jsx',
      '.storybook/ts',
      '.storybook/tsx',
      '.storybook/mdx',

      'storybook/js',
      'storybook/jsx',
      'storybook/ts',
      'storybook/tsx',
      'storybook/mdx',

      'stories/js',
      'stories/jsx',
      'stories/ts',
      'stories/tsx',
      'stories/mdx',
    ],
    name: 'storybookfiles',
  },
  {
    fileExtensions: [
      'stylelintrc',
      'stylelintrc.cjs',
      'stylelintrc.js',
      'stylelintrc.json',
      'stylelintrc.mjs',
      'stylelintrc.yaml',
      'stylelintrc.yml',
    ],
    fileNames: [
      'stylelint.config.cjs',
      'stylelint.config.js',
      'stylelint.config.json',
      'stylelint.config.mjs',
      'stylelint.config.ts',
      'stylelint.config.yaml',
      'stylelint.config.yml',
    ],
    name: 'stylelint',
  },
  {
    fileExtensions: ['stylelintignore', 'stylelintignore.json'],
    name: 'stylelintignore',
  },
  {
    fileExtensions: [
      'styleguiderc',
      'styleguiderc.cjs',
      'styleguiderc.js',
      'styleguiderc.json',
      'styleguiderc.mjs',
      'styleguiderc.yaml',
      'styleguiderc.yml',
    ],
    fileNames: [
      'styleguide.config.cjs',
      'styleguide.config.js',
      'styleguide.config.json',
      'styleguide.config.mjs',
      'styleguide.config.ts',
      'styleguide.config.yaml',
      'styleguide.config.yml',
    ],
    name: 'styleguidist',
  },
  {
    fileExtensions: ['st.css'],
    name: 'stylable',
  },
  {
    fileExtensions: [
      'sc.cjs',
      'sc.js',
      'sc.jsx',
      'sc.mdx',
      'sc.mjs',
      'sc.ts',
      'sc.tsx',
      'styled',
      'styled.cjs',
      'styled.js',
      'styled.jsx',
      'styled.mdx',
      'styled.mjs',
      'styled.ts',
      'styled.tsx',
      'styles.cjs',
      'styles.js',
      'styles.jsx',
      'styles.mdx',
      'styles.mjs',
      'styles.ts',
      'styles.tsx',
    ],
    name: 'styledcomponents',
  },
  {
    fileExtensions: ['stylish-haskell.yaml', 'stylish-haskell.yml'],
    name: 'stylishhaskell',
  },
  {
    fileExtensions: ['styl'],
    name: 'stylus',
  },
  {
    fileExtensions: ['sublime-macro', 'sublime-package', 'sublime-project', 'sublime-workspace'],
    name: 'sublime',
  },
  {
    fileExtensions: ['sbv', 'srt', 'sub'],
    name: 'subtitle',
  },
  {
    fileExtensions: ['scd', 'scsyndef', 'scsynthdef', 'scx', 'scxt', 'scz'],
    name: 'scd',
  },
  {
    fileExtensions: ['sss'],
    name: 'sss',
  },
  {
    fileNames: ['supabase.js', 'supabase.json', 'supabase.py', 'supabase.ts', 'supabase.yaml', 'supabase.yml'],
    name: 'supabase',
  },
  {
    fileExtensions: ['svelte', 'svelte-kit'],
    name: 'svelte',
  },
  {
    fileNames: [
      'svelte.config.cjs',
      'svelte.config.js',
      'svelte.config.json',
      'svelte.config.mjs',
      'svelte.config.ts',
      'svelte.config.yaml',
      'svelte.config.yml',
    ],
    name: 'svelte_config',
  },
  {
    fileExtensions: ['svgo.cjs', 'svgo.js', 'svgo.json', 'svgo.mjs', 'svgo.yaml', 'svgo.yml'],
    fileNames: [
      'svgo.config.cjs',
      'svgo.config.js',
      'svgo.config.json',
      'svgo.config.mjs',
      'svgo.config.ts',
      'svgo.config.yaml',
      'svgo.config.yml',
    ],
    name: 'svgo',
  },
  {
    fileExtensions: [
      'svgrrc',
      'svgrrc.cjs',
      'svgrrc.js',
      'svgrrc.json',
      'svgrrc.mjs',
      'svgrrc.ts',
      'svgrrc.yaml',
      'svgrrc.yml',
    ],
    fileNames: [
      'svgr.config.cjs',
      'svgr.config.js',
      'svgr.config.json',
      'svgr.config.mjs',
      'svgr.config.ts',
      'svgr.config.yaml',
      'svgr.config.yml',
    ],
    name: 'svgr',
  },
  {
    fileExtensions: ['mdsvex', 'svx'],
    name: 'svx',
  },
  {
    fileNames: ['screwdriver.yaml', 'screwdriver.yml'],
    name: 'screwdriver',
  },
  {
    fileExtensions: ['svn', 'svnignore'],
    name: 'svn',
  },
  {
    fileExtensions: ['slint'],
    name: 'slint',
  },
  {
    fileNames: ['sigstore.json'],
    name: 'sigstore',
  },
  {
    fileExtensions: ['swagger', 'swag'],
    fileNames: ['api.json', 'api.yaml', 'api.yml', 'swagger.json', 'swagger.yaml', 'swagger.yml'],
    name: 'swagger',
  },
  {
    fileExtensions: ['sw'],
    name: 'swlang',
  },
  {
    fileExtensions: ['swc'],
    name: 'swc',
  },
  {
    fileExtensions: ['swcrc'],
    name: 'swcrc',
  },
  {
    fileNames: ['package.pins', 'package.resolved'],
    name: 'swiftlock',
  },
  {
    fileExtensions: ['swig'],
    name: 'swig',
  },
  {
    fileNames: ['symfony.lock'],
    light: true,
    name: 'symfony',
  },
  {
    fileExtensions: [
      'syncpackrc',
      'syncpackrc.json',
      'syncpackrc.js',
      'syncpackrc.cjs',
      'syncpackrc.mjs',
      'syncpackrc.ts',
      'syncpackrc.yaml',
      'syncpackrc.yml',
    ],
    fileNames: [
      'syncpack.config.cjs',
      'syncpack.config.js',
      'syncpack.config.json',
      'syncpack.config.mjs',
    ],
    name: 'syncpack',
  },
];
