export const tFiles = [
  {
    fileExtensions: ['listing', 'toc'],
    name: 'toc',
  },
  {
    fileExtensions: ['tailwind.cjs', 'tailwind.js', 'tailwind.mjs', 'tailwind.ts'],
    fileNames: [
      'tailwind.conf.cjs',
      'tailwind.conf.js',
      'tailwind.conf.mjs',
      'tailwind.conf.ts',
      'tailwind.config.cjs',
      'tailwind.config.js',
      'tailwind.config.mjs',
      'tailwind.config.ts',
      'tailwind.js',
    ],
    name: 'tailwindcss',
  },
  {
    fileNames: [
      'tauri.cjs',
      'tauri.conf.cjs',
      'tauri.conf.js',
      'tauri.conf.json',
      'tauri.conf.mjs',
      'tauri.conf.ts',
      'tauri.config.cjs',
      'tauri.config.js',
      'tauri.config.mjs',
      'tauri.config.ts',
      'tauri.js',
      'tauri.mjs',
      'tauri.ts',
    ],
    name: 'tauri',
  },
  {
    fileExtensions: ['taurignore'],
    name: 'taurignore',
  },
  {
    fileExtensions: ['adp', 'exp', 'itcl', 'itk', 'tcl', 'tkdiffrc', 'tkvcs', 'tm'],
    name: 'tcl',
  },
  {
    fileExtensions: ['tea'],
    name: 'tea',
  },
  {
    fileExtensions: ['teal'],
    name: 'teal',
  },
  {
    fileExtensions: ['tl', 'xps'],
    name: 'telegram',
  },
  {
    fileExtensions: ['tt', 'tt2', 'tt3', 'tt4', 'ttml'],
    name: 'tt',
  },
  {
    fileExtensions: ['tera'],
    name: 'tera',
  },
  {
    fileExtensions: [
      'tf',
      'tf.json',
      'tfplan',
      'tfplan.json',
      'tfstate',
      'tfstate.json',
      'tfvars',
      'tfvars.json',
      'tfbackend',
      'tfbackend.json',
      'tfignore',
      'tfignore.json',
    ],
    name: 'terraform',
  },
  {
    fileExtensions: [
      'terserignore',
      'terserrc',
      'terserrc.conf',
      'terserrc.json',
      'uglifyignore',
      'uglifyrc',
      'uglifyrc.json',
    ],
    name: 'terser',
  },
  {
    fileExtensions: ['tern-config', 'tern-project', 'ternconfig'],
    name: 'tern',
  },
  {
    fileExtensions: ['testcaferc', 'testcaferc.json'],
    name: 'testcafe',
  },
  {
    fileExtensions: ['aux', 'dtx', 'lbx', 'ltx', 'mkii', 'mkiv', 'mkvi', 'pgf', 'sty', 'tex', 'texi', 'tikz', 'txi'],
    name: 'tex',
  },
  {
    fileExtensions: ['textlintrc', 'textlintrc.json'],
    name: 'textlint',
  },
  {
    fileExtensions: ['textile'],
    name: 'textile',
  },
  {
    fileExtensions: [
      'tmBundle',
      'tmCommand',
      'tmLanguage',
      'tmMacro',
      'tmPreferences',
      'tmProperties',
      'tmSnippet',
      'tmTheme',
      'tmcg',
    ],
    name: 'textmate',
  },
  {
    fileExtensions: ['thor'],
    name: 'thor',
  },
  {
    fileNames: [
      'thunder-collection.js',
      'thunder-collection.json',
      'thunder-collection_Web.json',
      'thunder-tests.js',
      'thunder-tests.json',
      'thunderclient.js',
      'thunderclient.json',
      'thunderclient.settings.js',
      'thunderclient.settings.json',
    ],
    name: 'thunderclient',
  },
  {
    fileExtensions: ['tidy', 'tidyparserrc', 'tidyparserrc.json'],
    name: 'tidyparse',
  },
  {
    fileNames: ['Tiltfile'],
    name: 'tilt',
  },
  {
    fileNames: [
      'tinymce.cjs',
      'tinymce.jquery.js',
      'tinymce.jquery.min.js',
      'tinymce.js',
      'tinymce.min.cjs',
      'tinymce.min.js',
      'tinymce.min.mjs',
      'tinymce.mjs',
      'tinymce.ts',
    ],
    name: 'tinymce',
  },
  {
    fileExtensions: ['tipe'],
    name: 'tipe',
  },
  {
    fileExtensions: ['tla'],
    name: 'tla',
  },
  {
    fileExtensions: ['tmux', 'tmux.conf'],
    fileNames: ['tmux.conf'],
    name: 'tmux',
  },
  {
    fileExtensions: ['truffle.cjs', 'truffle.js', 'truffle.mjs', 'truffle.ts'],
    fileNames: [
      'truffle-config.cjs',
      'truffle-config.js',
      'truffle-config.mjs',
      'truffle-config.ts',
      'truffle.cjs',
      'truffle.js',
      'truffle.mjs',
      'truffle.ts',
    ],
    name: 'truffle',
  },
  {
    fileExtensions: ['ttcn', 'ttcn3'],
    name: 'ttcn',
  },
  {
    fileNames: ['context.xml', 'server.xml', 'tomcat-users.xml', 'tomcat.conf', 'tomcat.java', 'web.xml'],
    name: 'tomcat',
  },
  {
    fileExtensions: ['taskpaper', 'todo'],
    name: 'todofile',
  },
  {
    fileNames: [
      'todo',
      'todo.adoc',
      'todo.c',
      'todo.cjs',
      'todo.conf',
      'todo.cpp',
      'todo.cs',
      'todo.cson',
      'todo.css',
      'todo.dart',
      'todo.go',
      'todo.h',
      'todo.htm',
      'todo.html',
      'todo.ini',
      'todo.java',
      'todo.js',
      'todo.json',
      'todo.jsx',
      'todo.kt',
      'todo.less',
      'todo.m',
      'todo.md',
      'todo.mjs',
      'todo.php',
      'todo.pl',
      'todo.plist',
      'todo.pm',
      'todo.pod',
      'todo.properties',
      'todo.py',
      'todo.rb',
      'todo.rst',
      'todo.scala',
      'todo.scss',
      'todo.sh',
      'todo.styl',
      'todo.swift',
      'todo.tex',
      'todo.texi',
      'todo.texinfo',
      'todo.toml',
      'todo.ts',
      'todo.tsx',
      'todo.txt',
      'todo.xml',
      'todo.yaml',
      'todo.yml',
    ],
    name: 'todo',
  },
  {
    fileExtensions: ['toit'],
    name: 'toit',
  },
  {
    fileNames: ['tikuiconfig.json'],
    name: 'tikui',
  },
  {
    fileNames: ['tsr.config.json'],
    name: 'tanstack',
  },
  {
    fileNames: ['tox.ini'],
    name: 'tox',
  },
  {
    fileExtensions: ['trunk'],
    fileNames: ['trunk.yaml', 'trunk.yml'],
    light: true,
    name: 'trunk',
  },
  {
    fileExtensions: [
      'tsconfig.cjs',
      'tsconfig.js',
      'tsconfig.json',
      'tsconfig.mjs',
      'tsconfig.ts',
      'tsconfig.yaml',
      'tsconfig.yml',
    ],
    fileNames: [
      'tsconfig.base.json',
      'tsconfig.build.json',
      'tsconfig.cjs',
      'tsconfig.eslint.json',
      'tsconfig.js',
      'tsconfig.json',
      'tsconfig.lib.json',
      'tsconfig.mjs',
      'tsconfig.spec.json',
      'tsconfig.ts',
      'tsconfig.yaml',
      'tsconfig.yml',
    ],
    name: 'tsconfig',
  },
  {
    fileExtensions: [
      'tslint.cjs',
      'tslint.js',
      'tslint.json',
      'tslint.mjs',
      'tslint.ts',
      'tslint.yaml',
      'tslint.yml',
    ],
    fileNames: [
      'tslint.base.json',
      'tslint.build.json',
      'tslint.cjs',
      'tslint.eslint.json',
      'tslint.js',
      'tslint.json',
      'tslint.lib.json',
      'tslint.mjs',
      'tslint.spec.json',
      'tslint.ts',
      'tslint.yaml',
      'tslint.yml',
    ],
    name: 'tslint',
  },
  {
    fileExtensions: ['travis.yml', 'travis.yaml'],
    name: 'travis',
  },
  {
    fileExtensions: ['tuc'],
    name: 'tuc',
  },
  {
    fileNames: ['turbo.config.cjs', 'turbo.config.js', 'turbo.config.mjs', 'turbo.config.ts', 'turbo.json'],
    name: 'turborepo',
  },
  {
    fileExtensions: ['tu'],
    name: 'turing',
  },
  {
    fileExtensions: ['twig'],
    name: 'twig',
  },
  {
    fileExtensions: ['tw', 'twee'],
    name: 'twine',
  },
  {
    fileExtensions: ['txl'],
    name: 'txl',
  },
  {
    fileNames: ['typedoc.cjs', 'typedoc.js', 'typedoc.json', 'typedoc.mjs', 'typedoc.ts'],
    name: 'typedoc',
  },
  {
    fileExtensions: ['d.ts'],
    name: 'dts',
  },
  {
    fileNames: ['typings.json'],
    name: 'typings',
  },
  {
    fileExtensions: ['typoscript'],
    name: 'typo3',
  },
];
