export const tests = [
  {
    fileExtensions: [
      'spec.coffee',
      'spec.litcoffee',
      'spec/coffee',
      'spec/litcoffee',
      'specs/coffee',
      'specs/litcoffee',
      'test.coffee',
      'test.litcoffee',
      'test/coffee',
      'test/litcoffee',
      'tests/coffee',
      'tests/litcoffee',
    ],
    name: 'testcoffee',
  },
  {
    fileExtensions: ['spec.dart', 'spec/dart', 'specs/dart', 'test.dart', 'test/dart', 'tests/dart'],
    name: 'testdart',
  },
  {
    fileExtensions: ['spec.go', 'spec/go', 'specs/go', 'test.go', 'test/go', 'tests/go'],
    name: 'testgo',
  },
  {
    fileExtensions: ['spec.hs', 'spec/hs', 'specs/hs', 'test.hs', 'test/hs', 'tests/hs'],
    name: 'testhaskell',
  },
  {
    fileExtensions: ['junit/java', 'test/java', 'tests/java', 'unit/java'],
    name: 'testjava',
  },
  {
    fileExtensions: ['junit/kt', 'test/kt', 'tests/kt', 'unit/kt'],
    name: 'testkt',
  },
  {
    fileExtensions: [
      'spec.cjs',
      'spec.es6',
      'spec.js',
      'spec.mjs',
      'spec/cjs',
      'spec/es6',
      'spec/js',
      'spec/mjs',
      'specs/cjs',
      'specs/es6',
      'specs/js',
      'specs/mjs',
      'test.cjs',
      'test.es6',
      'test.js',
      'test.mjs',
      'test/cjs',
      'test/es6',
      'test/js',
      'test/mjs',
      'tests/cjs',
      'tests/es6',
      'tests/js',
      'tests/mjs',
    ],
    light: true,
    name: 'testjs',
  },
  {
    fileExtensions: [
      'spec.perl',
      'spec.ph',
      'spec.pl',
      'spec.pl6',
      'spec.pm6',
      'spec/perl',
      'spec/ph',
      'spec/pl',
      'spec/pl6',
      'spec/pm6',
      'specs/perl',
      'specs/ph',
      'specs/pl',
      'specs/pl6',
      'specs/pm6',
      'test.perl',
      'test.ph',
      'test.pl',
      'test.pl6',
      'test.pm6',
      'test/perl',
      'test/ph',
      'test/pl',
      'test/pl6',
      'test/pm6',
      'tests/perl',
      'tests/ph',
      'tests/pl',
      'tests/pl6',
      'tests/pm6',
    ],
    name: 'testperl',
  },
  {
    fileExtensions: [
      'spec.jsx',
      'spec.tsx',
      'spec/jsx',
      'spec/tsx',
      'specs/jsx',
      'specs/tsx',
      'test.jsx',
      'test.tsx',
      'test/jsx',
      'test/tsx',
      'tests/jsx',
      'tests/tsx',
    ],
    name: 'testreact',
  },
  {
    fileExtensions: [
      'spec.ipy',
      'spec.pep',
      'spec.py',
      'spec.py3',
      'spec.python',
      'spec.whl',
      'spec/ipy',
      'spec/pep',
      'spec/py',
      'spec/py3',
      'spec/python',
      'spec/whl',
      'specs/ipy',
      'specs/pep',
      'specs/py',
      'specs/py3',
      'specs/python',
      'specs/whl',
      'test.ipy',
      'test.pep',
      'test.py',
      'test.py3',
      'test.python',
      'test.whl',
      'test/ipy',
      'test/pep',
      'test/py',
      'test/py3',
      'test/python',
      'test/whl',
      'tests/ipy',
      'tests/pep',
      'tests/py',
      'tests/py3',
      'tests/python',
      'tests/whl',
    ],
    name: 'testpy',
  },
  {
    fileExtensions: [
      'spec.rb',
      'spec.rbs',
      'spec.ruby',
      'spec/rb',
      'spec/rbs',
      'spec/ruby',
      'specs/rb',
      'specs/rbs',
      'specs/ruby',
      'test.rb',
      'test.rbs',
      'test.ruby',
      'test/rb',
      'test/rbs',
      'test/ruby',
      'tests/rb',
      'tests/rbs',
      'tests/ruby',
    ],
    name: 'testruby',
  },
  {
    fileExtensions: ['spec.rs', 'spec/rs', 'specs/rs', 'test.rs', 'test/rs', 'tests/rs'],
    name: 'testrust',
  },
  {
    fileExtensions: ['spec.scala', 'spec/scala', 'specs/scala', 'test.scala', 'test/scala', 'tests/scala'],
    name: 'testscala',
  },
  {
    fileExtensions: ['spec.ts', 'spec/ts', 'specs/ts', 'test.ts', 'test/ts', 'tests/ts'],
    name: 'testts',
  },
  {
    fileExtensions: [
      'spec.php',
      'spec/php',
      'specs/php',
      'test.php',
      'test/php',
      'tests/php',
      'unit.php',
      'unit/php',
      'units/php',
      'phpunit/php',
    ],
    name: 'testphp',
  },
];
