export const uFiles = [
  {
    fileExtensions: ['glif', 'ufo', 'ufoz'],
    name: 'ufo',
  },
  {
    fileNames: ['uikit.cjs', 'uikit.js', 'uikit.min.cjs', 'uikit.min.js', 'uikit.min.mjs', 'uikit.mjs'],
    name: 'uikit',
  },
  {
    fileExtensions: ['umirc', 'umirc.js', 'umirc.ts', 'umirc.tsx', 'umirc.cjs', 'umirc.jsx', 'umirc.mjs'],
    name: 'umi',
  },
  {
    fileExtensions: ['iuml', 'plantuml', 'pu', 'puml', 'uml', 'wsd'],
    name: 'uml',
  },
  {
    fileExtensions: ['unicode'],
    name: 'unicode',
  },
  {
    fileExtensions: [
      'unibeautifyrc.cjs',
      'unibeautifyrc.js',
      'unibeautifyrc.json',
      'unibeautifyrc.mjs',
      'unibeautifyrc.ts',
      'unibeautifyrc.yaml',
      'unibeautifyrc.yml',
    ],
    fileNames: [
      'unibeautify.config.cjs',
      'unibeautify.config.js',
      'unibeautify.config.json',
      'unibeautify.config.mjs',
      'unibeautify.config.ts',
      'unibeautify.config.yaml',
      'unibeautify.config.yml',
    ],
    name: 'unibeautify',
  },
  {
    fileExtensions: ['unibeautifyrc'],
    fileNames: [
      'unibeautifyrc.config.cjs',
      'unibeautifyrc.config.js',
      'unibeautifyrc.config.json',
      'unibeautifyrc.config.mjs',
      'unibeautifyrc.config.ts',
      'unibeautifyrc.config.yaml',
      'unibeautifyrc.config.yml',
    ],
    name: 'unibeautifyrc',
  },
  {
    fileExtensions: [
      'anim',
      'asset',
      'cubemap',
      'meta',
      'ply',
      'prefab',
      'u3d',
      'unity',
      'unity3d',
      'unitypackage',
      'unityproj',
    ],
    name: 'unity',
  },
  {
    fileExtensions: ['uof', 'uop', 'uos', 'uot'],
    name: 'uos',
  },
  {
    fileExtensions: ['u'],
    name: 'unison',
  },
  {
    fileNames: [
      'unlicence',
      'unlicence.md',
      'unlicence.rst',
      'unlicence.txt',
      'unlicense',
      'unlicense.md',
      'unlicense.rst',
      'unlicense.txt',
    ],
    name: 'unlicense',
  },
  {
    fileExtensions: ['uno', 'unoproj'],
    name: 'uno',
  },
  {
    fileNames: [
      'uno.config.cjs',
      'uno.config.js',
      'uno.config.mjs',
      'uno.config.ts',
      'unocss.config.cjs',
      'unocss.config.js',
      'unocss.config.mjs',
      'unocss.config.ts',
    ],
    name: 'unocss',
  },
  {
    fileExtensions: [
      'uasset',
      'uax',
      'uc',
      'ukx',
      'umap',
      'umx',
      'unr',
      'upkg',
      'upl',
      'uplugin',
      'uproject',
      'utx',
      'uz',
    ],
    name: 'unreal',
  },
  {
    fileExtensions: ['ur', 'urs'],
    name: 'urweb',
  },
];
